export const DOC_TYPES = [
    {
        id: "invoice",
        label: "GST Invoice",
        href: "/invoice",
        description: "Tax invoice with CGST, SGST & IGST",
        icon: "📄",
    },
    {
        id: "quotation",
        label: "Quotation",
        href: "/quotation",
        description: "Price quotes for clients",
        icon: "💬",
    },
    {
        id: "receipt",
        label: "Receipt",
        href: "/receipt",
        description: "Payment receipt generator",
        icon: "🧾",
    },
    {
        id: "salary-slip",
        label: "Salary Slip",
        href: "/salary-slip",
        description: "Payslip with PF, TDS & allowances",
        icon: "💰",
    },
    {
        id: "certificate",
        label: "Certificate",
        href: "/certificate",
        description: "Bulk verified certificates with QR",
        icon: "🏆",
    },
    {
        id: "proforma-invoice",
        label: "Proforma Invoice",
        href: "/proforma-invoice",
        description: "Advance billing document",
        icon: "📋",
    },
    {
        id: "experience-letter",
        label: "Experience Letter",
        href: "/experience-letter",
        description: "HR experience certificates",
        icon: "✉️",
    },
    {
        id: "resignation-letter",
        label: "Resignation Letter",
        href: "/resignation-letter",
        description: "Professional resignation format",
        icon: "📝",
    },
    {
        id: "job-offer-letter",
        label: "Job Offer Letter",
        href: "/job-offer-letter",
        description: "Formal offer letter template",
        icon: "🤝",
    },
    {
        id: "internship-certificate",
        label: "Internship Certificate",
        href: "/internship-certificate",
        description: "Internship completion certificate",
        icon: "🎓",
    },
    {
        id: "purchase-order",
        label: "Purchase Order",
        href: "/purchase-order",
        description: "PO for vendors and suppliers",
        icon: "🛒",
    },
    {
        id: "packing-slip",
        label: "Packing Slip",
        href: "/packing-slip",
        description: "Shipment packing list",
        icon: "📦",
    },
    {
        id: "rent-receipt",
        label: "Rent Receipt",
        href: "/rent-receipt",
        description: "Monthly rent receipt for HRA",
        icon: "🏠",
    },
    {
        id: "payment-voucher",
        label: "Payment Voucher",
        href: "/payment-voucher",
        description: "Internal payment records",
        icon: "💳",
    },
];