"use client";
import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";

export default function JobOfferElegantTemplate({ form }) {
  const T = form.templateColor || "#D97706";
  const ctc = parseFloat(form.ctcAmount) || 0;
  const fmt = (n) => Math.round(n).toLocaleString("en-IN");

  const styles = StyleSheet.create({
    page: { fontFamily: "Helvetica", fontSize: 10, color: "#111827", padding: "50 70", background: "#FFFDFA" },
    header: { marginBottom: 40, borderBottomWidth: 1, borderBottomColor: "#E5E7EB", paddingBottom: 20 },
    title: { fontSize: 24, fontFamily: "Helvetica-Bold", color: T, marginBottom: 8, letterSpacing: 1 },
    subtitle: { fontSize: 9, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: 2 },
    dateLine: { fontSize: 9, color: "#6B7280", marginBottom: 30, textAlign: "right" },
    toBox: { marginBottom: 30 },
    toName: { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#111827", marginBottom: 2 },
    toSub: { fontSize: 9, color: "#6B7280" },
    body: { fontSize: 10, color: "#374151", lineHeight: 2, marginBottom: 16 },
    highlight: { color: T, fontFamily: "Helvetica-Bold" },
    ctcBox: { margin: "20 0", padding: "16 0", borderTopWidth: 1, borderTopColor: T, borderBottomWidth: 1, borderBottomColor: T },
    ctcLabel: { fontSize: 8, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: 1, marginBottom: 4 },
    ctcVal: { fontSize: 20, fontFamily: "Helvetica-Bold", color: T },
    signImg: { height: 45, marginBottom: 5, objectFit: "contain" },
    signLine: { borderTopWidth: 1, borderTopColor: T, paddingTop: 8, width: 160 },
    signName: { fontSize: 12, fontFamily: "Helvetica-Bold", color: "#111827" },
    signDesig: { fontSize: 9, color: "#9CA3AF", marginTop: 2 },
    borderBottom: { position: "absolute", bottom: 0, left: 0, right: 0, height: 6, background: T },
    footerGen: { position: "absolute", bottom: 30, left: 70, fontSize: 8, color: "#D1D5DB" },
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>OFFER LETTER</Text>
          <Text style={styles.subtitle}>{form.companyName || "Professional Employment Offer"}</Text>
        </View>
        <Text style={styles.dateLine}>{"Reference: " + form.letterNumber + "  |  Date: " + form.letterDate}</Text>
        <View style={styles.toBox}>
          <Text style={styles.toName}>{form.candidateName || "Candidate Name"}</Text>
          <Text style={styles.toSub}>{form.candidateAddress || ""}</Text>
        </View>
        <Text style={styles.body}>Dear {form.candidateName ? form.candidateName.split(" ")[0] : "Candidate"},</Text>
        <Text style={styles.body}>
          We are delighted to extend this offer of employment to you for the position of <Text style={styles.highlight}>{form.designation || "[Designation]"}</Text> 
          {form.department ? " in the " + form.department + " department" : ""} at <Text style={styles.highlight}>{form.companyName || "[Company]"}</Text>.
        </Text>
        <Text style={styles.body}>Your start date will be <Text style={styles.highlight}>{form.dateOfJoining || "TBD"}</Text>. Your employment status will be {form.employmentType}.</Text>
        {ctc > 0 && (
          <View style={styles.ctcBox}>
            <Text style={styles.ctcLabel}>Total Annual Compensation (CTC)</Text>
            <Text style={styles.ctcVal}>{"Rs. " + fmt(ctc)}</Text>
          </View>
        )}
        {form.additionalTerms && <Text style={styles.body}>{form.additionalTerms}</Text>}
        <Text style={styles.body}>We are confident that you will make a significant contribution to our organization. Please confirm your acceptance by {form.acceptanceDeadline || "the earliest"}.</Text>
        <View style={{ marginTop: 30, flexDirection: "row", justifyContent: "space-between" }}>
          <View>
            {form.signature && <Image src={form.signature} style={styles.signImg} />}
            <View style={styles.signLine}>
              <Text style={styles.signName}>{form.signatoryName || "HR Manager"}</Text>
              <Text style={styles.signDesig}>{form.signatoryDesignation || ""}</Text>
            </View>
          </View>
          <View style={styles.signLine}><Text style={styles.signName}>Candidate Signature</Text></View>
        </View>
        <Text style={styles.footerGen}>Generated by DocMinty.com</Text>
        <View style={styles.borderBottom} />
      </Page>
    </Document>
  );
}
