"use client";
import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";

export default function JobOfferMinimalTemplate({ form }) {
  const T = form.templateColor || "#111827";
  const ctc = parseFloat(form.ctcAmount) || 0;
  const fmt = (n) => Math.round(n).toLocaleString("en-IN");

  const styles = StyleSheet.create({
    page: { fontFamily: "Helvetica", fontSize: 10, color: "#374151", padding: "40 50" },
    top: { borderBottomWidth: 1.5, borderBottomColor: T, paddingBottom: 12, marginBottom: 24, flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" },
    title: { fontSize: 13, fontFamily: "Helvetica-Bold", color: "#111827", textTransform: "uppercase", letterSpacing: 1 },
    date: { fontSize: 9, color: "#9CA3AF" },
    meta: { marginBottom: 24 },
    label: { fontSize: 7, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 2 },
    value: { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#111827" },
    bodyText: { fontSize: 10, color: "#374151", lineHeight: 1.7, marginBottom: 12 },
    lastDay: { color: T, fontFamily: "Helvetica-Bold" },
    ctcRow: { flexDirection: "row", justifyContent: "space-between", padding: "8 0", borderTopWidth: 1, borderTopColor: "#E5E7EB", marginBottom: 12 },
    ctcLabel: { fontSize: 10, fontFamily: "Helvetica-Bold", color: "#111827" },
    ctcVal: { fontSize: 10, fontFamily: "Helvetica-Bold", color: T },
    signRow: { marginTop: 40, flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" },
    signImg: { height: 35, marginBottom: 5, objectFit: "contain" },
    signLine: { borderTopWidth: 1, borderTopColor: "#111827", paddingTop: 5, width: 140 },
    signName: { fontSize: 10, fontFamily: "Helvetica-Bold", color: "#111827" },
    signGen: { fontSize: 7, color: "#D1D5DB", position: "absolute", bottom: 20, left: 50 },
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.top}>
          <Text style={styles.title}>Offer Letter</Text>
          <Text style={styles.date}>{form.letterDate}</Text>
        </View>
        <View style={{ flexDirection: "row", justifyContent: "space-between", marginBottom: 24 }}>
          <View>
            <Text style={styles.label}>To</Text>
            <Text style={styles.value}>{form.candidateName || "Candidate Name"}</Text>
            {form.candidateAddress && <Text style={{ fontSize: 9, color: "#6B7280", marginTop: 2, width: 180 }}>{form.candidateAddress}</Text>}
          </View>
          <View style={{ textAlign: "right" }}>
            <Text style={styles.label}>From</Text>
            <Text style={styles.value}>{form.companyName || "Company Name"}</Text>
            <Text style={styles.date}>Ref: {form.letterNumber}</Text>
          </View>
        </View>
        <Text style={styles.bodyText}>Dear {form.candidateName ? form.candidateName.split(" ")[0] : "Candidate"},</Text>
        <Text style={styles.bodyText}>
          We are pleased to offer you the position of <Text style={{ fontFamily: "Helvetica-Bold" }}>{form.designation || "[Designation]"}</Text> 
          {form.department ? " in the " + form.department + " department" : ""} at <Text style={{ fontFamily: "Helvetica-Bold" }}>{form.companyName || "[Company]"}</Text>.
        </Text>
        <View style={{ margin: "12 0" }}>
          <Text style={styles.bodyText}>- Your joining date will be <Text style={{ fontFamily: "Helvetica-Bold", color: T }}>{form.dateOfJoining || "TBD"}</Text>.</Text>
          <Text style={styles.bodyText}>- You will be working as a <Text style={{ fontFamily: "Helvetica-Bold" }}>{form.employmentType}</Text>.</Text>
          <Text style={styles.bodyText}>- Probation Period: {form.probationPeriod || "0"} Months.</Text>
        </View>
        {ctc > 0 && <View style={styles.ctcRow}><Text style={styles.ctcLabel}>Total Compensation (Annual CTC)</Text><Text style={styles.ctcVal}>{"Rs. " + fmt(ctc)}</Text></View>}
        {form.additionalTerms && <Text style={styles.bodyText}>{form.additionalTerms}</Text>}
        <Text style={styles.bodyText}>We look forward to your positive response by {form.acceptanceDeadline || "the earliest"}.</Text>
        <View style={styles.signRow}>
          <View>
            {form.signature && <Image src={form.signature} style={styles.signImg} />}
            <View style={styles.signLine}>
              <Text style={styles.signName}>{form.signatoryName || "HR Manager"}</Text>
              <Text style={{ fontSize: 8, color: "#9CA3AF" }}>{form.signatoryDesignation}</Text>
            </View>
          </View>
          <View style={styles.signLine}>
            <Text style={styles.signName}>Candidate Signature</Text>
          </View>
        </View>
        <Text style={styles.signGen}>Generated by DocMinty.com</Text>
      </Page>
    </Document>
  );
}
