"use client";
import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";

export default function JobOfferModernTemplate({ form }) {
  const T = form.templateColor || "#6366F1";
  const ctc = parseFloat(form.ctcAmount) || 0;
  const fmt = (n) => Math.round(n).toLocaleString("en-IN");

  const styles = StyleSheet.create({
    page: { fontFamily: "Helvetica", fontSize: 10, color: "#111827", padding: 0, flexDirection: "row" },
    sidebar: { width: "160pt", background: T, height: "100%", padding: "40 24", color: "#fff" },
    sideTitle: { fontSize: 16, fontFamily: "Helvetica-Bold", textTransform: "uppercase", letterSpacing: 2, marginBottom: 30 },
    sideLabel: { fontSize: 8, color: "rgba(255,255,255,0.7)", textTransform: "uppercase", letterSpacing: 1, marginBottom: 4 },
    sideValue: { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#fff", marginBottom: 20 },
    main: { flex: 1, padding: "50 40", background: "#fff" },
    header: { marginBottom: 30 },
    date: { fontSize: 9, color: "#9CA3AF", marginBottom: 16 },
    manager: { fontSize: 12, fontFamily: "Helvetica-Bold", color: "#111827" },
    managerDesig: { fontSize: 9, color: "#6B7280", marginTop: 2 },
    body: { fontSize: 10, color: "#374151", lineHeight: 1.8, marginBottom: 12 },
    lastDay: { color: T, fontFamily: "Helvetica-Bold" },
    ctcBox: { backgroundColor: "#F3F4F6", padding: "12 16", borderRadius: 8, margin: "14 0" },
    ctcVal: { fontSize: 16, fontFamily: "Helvetica-Bold", color: T },
    signImg: { height: 40, marginBottom: 5, objectFit: "contain" },
    signLine: { borderTopWidth: 1.5, borderTopColor: "#111827", paddingTop: 6, width: 150 },
    signName: { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#111827" },
    signDesig: { fontSize: 9, color: "#9CA3AF", marginTop: 2 },
    footer: { position: "absolute", bottom: 40, left: 40, borderTopWidth: 1, borderTopColor: "#E5E7EB", width: "100%", paddingTop: 10 },
    footerGen: { fontSize: 7, color: "#D1D5DB" },
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.sidebar}>
          <Text style={styles.sideTitle}>Job Offer</Text>
          <View>
            <Text style={styles.sideLabel}>Company</Text>
            <Text style={styles.sideValue}>{form.companyName || "Company Name"}</Text>
          </View>
          <View>
            <Text style={styles.sideLabel}>Joining Date</Text>
            <Text style={styles.sideValue}>{form.dateOfJoining || "—"}</Text>
          </View>
          <View>
            <Text style={styles.sideLabel}>Position</Text>
            <Text style={styles.sideValue}>{form.designation || "Role"}</Text>
          </View>
        </View>
        <View style={styles.main}>
          <View style={styles.header}>
            <Text style={styles.date}>{"Dated: " + form.letterDate}</Text>
            <Text style={styles.manager}>{form.candidateName || "Candidate Name"}</Text>
            <Text style={styles.managerDesig}>{form.candidateAddress || ""}</Text>
          </View>
          <Text style={styles.body}>Dear {form.candidateName ? form.candidateName.split(" ")[0] : "Candidate"},</Text>
          <Text style={styles.body}>
            We are excited to offer you the position of <Text style={{ fontFamily: "Helvetica-Bold" }}>{form.designation || "[Designation]"}</Text> 
            {form.department ? " in the " + form.department + " department" : ""} at <Text style={{ fontFamily: "Helvetica-Bold" }}>{form.companyName || "[Company]"}</Text>.
          </Text>
          <Text style={styles.body}>You will be joining our team on <Text style={styles.lastDay}>{form.dateOfJoining || "TBD"}</Text>. Your employment type will be {form.employmentType}.</Text>
          {ctc > 0 && (
            <View style={styles.ctcBox}>
              <Text style={styles.sideLabel}>Total Compensation (Annual CTC)</Text>
              <Text style={styles.ctcVal}>{"Rs. " + fmt(ctc)}</Text>
            </View>
          )}
          {form.additionalTerms && <Text style={styles.body}>{form.additionalTerms}</Text>}
          <Text style={styles.body}>Please confirm your acceptance by {form.acceptanceDeadline || "the earliest"}. We are looking forward to working with you.</Text>
          <View style={{ marginTop: 24 }}>
            {form.signature && <Image src={form.signature} style={styles.signImg} />}
            <View style={styles.signLine}>
              <Text style={styles.signName}>{form.signatoryName || "HR Manager"}</Text>
              <Text style={styles.signDesig}>{form.signatoryDesignation || ""}</Text>
            </View>
          </View>
          <View style={styles.footer}><Text style={styles.footerGen}>Generated by DocMinty.com</Text></View>
        </View>
      </Page>
    </Document>
  );
}
