"use client";
import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";

const PERF_TEXT = {
  excellent: "exceptional commitment, creativity, and technical skills",
  good: "good work ethic and contributed meaningfully to the team",
  satisfactory: "performed their assigned duties satisfactorily",
};

export default function InternshipElegantTemplate({ form }) {
  const T = form.templateColor || "#7C3AED";
  const perfText = PERF_TEXT[form.performance] || PERF_TEXT.good;
  const start = form.startDate ? new Date(form.startDate).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" }) : "Start Date";
  const end = form.endDate ? new Date(form.endDate).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" }) : "End Date";

  const styles = StyleSheet.create({
    page: { fontFamily: "Helvetica", fontSize: 10, color: "#111827", padding: "50 70", background: "#FFFDFA" },
    sidebarLine: { position: "absolute", left: 30, top: 50, bottom: 50, width: 2, background: T },
    header: { marginBottom: 40 },
    title: { fontSize: 28, fontFamily: "Helvetica-Bold", color: T, marginBottom: 8, letterSpacing: 2 },
    subtitle: { fontSize: 10, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: 3 },
    orgHeader: { flexDirection: "row", alignItems: "center", marginBottom: 30, marginTop: 40 },
    logo: { height: 35, objectFit: "contain", marginRight: 15 },
    orgName: { fontSize: 14, fontFamily: "Helvetica-Bold", color: "#111827" },
    certify: { fontSize: 11, color: "#9CA3AF", marginBottom: 12 },
    name: { fontSize: 26, fontFamily: "Helvetica-Bold", color: "#111827", marginBottom: 24 },
    body: { fontSize: 11, color: "#374151", lineHeight: 2, marginBottom: 24 },
    project: { fontSize: 10, fontFamily: "Helvetica-Bold", color: T, marginBottom: 40 },
    sigRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" },
    sigImg: { height: 40, marginBottom: 5, objectFit: "contain" },
    sigLine: { borderTopWidth: 1.5, borderTopColor: T, paddingTop: 8, width: 150 },
    sigName: { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#111827" },
    sigDesig: { fontSize: 9, color: "#9CA3AF", marginTop: 2 },
    footerGen: { position: "absolute", bottom: 40, left: 70, fontSize: 8, color: "#D1D5DB" },
    borderBottom: { position: "absolute", bottom: 0, left: 0, right: 0, height: 6, background: T },
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.sidebarLine} />
        <View style={styles.header}>
          <Text style={styles.title}>CERTIFICATE</Text>
          <Text style={styles.subtitle}>of Internship Excellence</Text>
        </View>
        <View style={styles.orgHeader}>
          {form.logo && <Image src={form.logo} style={styles.logo} />}
          <View>
            <Text style={styles.orgName}>{form.orgName || "Organisation"}</Text>
            {form.orgAddress && <Text style={{ fontSize: 8, color: "#9CA3AF" }}>{form.orgAddress}</Text>}
          </View>
        </View>
        <Text style={styles.certify}>Presented to</Text>
        <Text style={styles.name}>{form.internName || "Intern Name"}</Text>
        <Text style={styles.body}>This document certifies that <Text style={{ fontFamily: "Helvetica-Bold" }}>{form.internName || "Candidate"}</Text> successfully completed an internship as <Text style={{ color: T, fontFamily: "Helvetica-Bold" }}>{form.role || "Intern"}</Text>{form.department ? ` in the ${form.department} department` : ""} at <Text style={{ fontFamily: "Helvetica-Bold" }}>{form.orgName || "Organisation"}</Text> from {start} to {end}. During the program, the candidate demonstrated {perfText}.</Text>
        {form.projectName && <Text style={styles.project}>Project: {form.projectName}</Text>}
        <View style={styles.sigRow}>
          <View>
            {form.signature && <Image src={form.signature} style={styles.sigImg} />}
            <View style={styles.sigLine}>
              <Text style={styles.sigName}>{form.signatoryName || "Signatory"}</Text>
              <Text style={styles.sigDesig}>{form.signatoryDesignation || "Designation"}</Text>
            </View>
          </View>
          {form.enableQR && (
            <View style={{ textAlign: "right" }}>
              <Text style={{ fontSize: 7, color: T, fontFamily: "Helvetica-Bold", marginBottom: 2 }}>QR VERIFIED</Text>
              <Text style={{ fontSize: 7, color: "#9CA3AF", fontFamily: "Courier" }}>ID: {form.verificationId}</Text>
              <Text style={{ fontSize: 7, color: "#D1D5DB", marginTop: 2 }}>{form.issueDate}</Text>
            </View>
          )}
        </View>
        <Text style={styles.footerGen}>Generated by DocMinty.com</Text>
        <View style={styles.borderBottom} />
      </Page>
    </Document>
  );
}
