"use client";

import { useState, useCallback } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AdSense from "@/components/AdSense";
import { Download, Eye, RefreshCw } from "lucide-react";
import { useDownloadPDF } from "@/hooks/useDownloadPDF";

const T = "#0D9488";

const DEFAULT_FORM = {
  employeeName: "",
  designation: "",
  department: "",
  companyName: "",
  managerName: "",
  managerDesignation: "",
  letterDate: new Date().toISOString().split("T")[0],
  lastWorkingDate: "",
  noticePeriod: "30",
  reason: "personal",
  customReason: "",
  gratitudeNote: "",
};

const REASONS = {
  personal: "I have decided to pursue a new opportunity that aligns more closely with my personal and professional goals.",
  relocation: "Due to relocation constraints, I am unable to continue in my current position.",
  health: "Due to personal health reasons, I am unable to continue in my current role.",
  higher: "I have been offered an opportunity to pursue higher education, which requires my full commitment.",
  custom: "",
};

function ResignationPreview({ form }) {
  const reasonText = form.reason === "custom" ? form.customReason : REASONS[form.reason];

  return (
    <div className="pdf-preview">
      <div className="pdf-header">
        <div>
          <p style={{ fontFamily: "Space Grotesk, sans-serif", fontWeight: 700, fontSize: "16px", color: T, margin: 0 }}>RESIGNATION LETTER</p>
          <p style={{ fontSize: "11px", color: "#9CA3AF", margin: "4px 0 0", fontFamily: "Inter, sans-serif" }}>Date: {form.letterDate}</p>
        </div>
      </div>
      <div className="pdf-body">
        <p style={{ fontSize: "12px", color: "#374151", fontFamily: "Inter, sans-serif", margin: "0 0 4px" }}>
          <strong>{form.managerName || "Manager Name"}</strong>
        </p>
        <p style={{ fontSize: "12px", color: "#6B7280", fontFamily: "Inter, sans-serif", margin: "0 0 16px" }}>
          {form.managerDesignation || "Designation"}{form.companyName ? `, ${form.companyName}` : ""}
        </p>

        <p style={{ fontSize: "12px", color: "#374151", fontFamily: "Inter, sans-serif", margin: "0 0 12px" }}>Dear {form.managerName ? form.managerName.split(" ")[0] : "Sir/Madam"},</p>

        <p style={{ fontSize: "12px", color: "#374151", fontFamily: "Inter, sans-serif", lineHeight: 1.8, margin: "0 0 12px" }}>
          I am writing to formally notify you of my resignation from the position of{" "}
          <strong>{form.designation || "[Designation]"}</strong>
          {form.department ? ` in the ${form.department} department` : ""}
          {form.companyName ? ` at ${form.companyName}` : ""}.
          My last working day will be{" "}
          <strong style={{ color: T }}>{form.lastWorkingDate || "[Last Working Date]"}</strong>,
          serving a notice period of {form.noticePeriod} days.
        </p>

        {reasonText && (
          <p style={{ fontSize: "12px", color: "#374151", fontFamily: "Inter, sans-serif", lineHeight: 1.8, margin: "0 0 12px" }}>
            {reasonText}
          </p>
        )}

        <p style={{ fontSize: "12px", color: "#374151", fontFamily: "Inter, sans-serif", lineHeight: 1.8, margin: "0 0 12px" }}>
          {form.gratitudeNote || "I am grateful for the opportunities for professional and personal development that you have provided during my tenure. I have enjoyed working with the team and value the experience I have gained here."}
        </p>

        <p style={{ fontSize: "12px", color: "#374151", fontFamily: "Inter, sans-serif", lineHeight: 1.8, margin: "0 0 24px" }}>
          I will ensure a smooth transition and will complete all pending tasks before my last working day. Please let me know how I can assist during this transition period.
        </p>

        <p style={{ fontSize: "12px", color: "#374151", fontFamily: "Inter, sans-serif", margin: "0 0 32px" }}>
          Yours sincerely,
        </p>

        <div style={{ borderTop: "1px solid #374151", paddingTop: "6px", display: "inline-block", minWidth: "140px" }}>
          <p style={{ fontSize: "13px", fontWeight: 700, color: "#111827", margin: 0, fontFamily: "Space Grotesk, sans-serif" }}>{form.employeeName || "Employee Name"}</p>
          <p style={{ fontSize: "11px", color: "#6B7280", margin: "2px 0 0", fontFamily: "Inter, sans-serif" }}>{form.designation}</p>
          {form.department && <p style={{ fontSize: "11px", color: "#6B7280", margin: "2px 0 0", fontFamily: "Inter, sans-serif" }}>{form.department}</p>}
        </div>

        <div style={{ marginTop: "24px", paddingTop: "12px", borderTop: "1px solid #E5E7EB" }}>
          <p style={{ fontSize: "10px", color: "#D1D5DB", fontFamily: "Inter, sans-serif", margin: 0 }}>Generated by DocMinty.com</p>
        </div>
      </div>
    </div>
  );
}

export default function ResignationLetterPage() {
  const [form, setForm] = useState(DEFAULT_FORM);
  const { download, downloading } = useDownloadPDF();
  const handleDownload = () => download("ResignationLetter", form, "ResignationLetter.pdf");
  const updateField = useCallback((field, value) => setForm(prev => ({ ...prev, [field]: value })), []);

  return (
    <>
      <Navbar />
      <div style={{ background: "#fff", borderBottom: "1px solid #E5E7EB", padding: "14px 24px" }}>
        <div style={{ maxWidth: "1300px", margin: "0 auto", display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: "12px" }}>
          <div>
            <h1 style={{ fontFamily: "Space Grotesk, sans-serif", fontSize: "18px", fontWeight: 700, margin: 0, color: "#111827" }}>Resignation Letter Generator</h1>
            <p style={{ fontSize: "12px", color: "#9CA3AF", margin: "2px 0 0", fontFamily: "Inter, sans-serif" }}>Professional resignation format</p>
          </div>
          <div style={{ display: "flex", gap: "8px" }}>
            <button onClick={() => setForm(DEFAULT_FORM)} style={{ display: "flex", alignItems: "center", gap: "6px", height: "36px", padding: "0 14px", border: "1px solid #E5E7EB", borderRadius: "8px", background: "#fff", fontSize: "13px", fontWeight: 600, color: "#6B7280", cursor: "pointer", fontFamily: "Inter, sans-serif" }}><RefreshCw size={13} /> Reset</button>
            <button onClick={handleDownload} disabled={downloading} className="download-pdf-btn">

              <Download size={15} />

              {downloading ? "Generating..." : "Download PDF"}

            </button>
          </div>
        </div>
      </div>

      <div style={{ background: "#F0F4F3", minHeight: "calc(100vh - 120px)" }}>
        <div className="doc-page-wrap">
          <div className="form-panel">
            <p className="form-label">Your Details</p>
            <div className="form-field"><label className="field-label">Your Name *</label><input className="doc-input" placeholder="Full Name" value={form.employeeName} onChange={e => updateField("employeeName", e.target.value)} /></div>
            <div className="form-row">
              <div className="form-field" style={{ marginBottom: 0 }}><label className="field-label">Designation</label><input className="doc-input" placeholder="Sr. Developer" value={form.designation} onChange={e => updateField("designation", e.target.value)} /></div>
              <div className="form-field" style={{ marginBottom: 0 }}><label className="field-label">Department</label><input className="doc-input" placeholder="Engineering" value={form.department} onChange={e => updateField("department", e.target.value)} /></div>
            </div>
            <div style={{ borderTop: "1px solid #F3F4F6", margin: "16px 0" }} />
            <p className="form-label">Addressed To</p>
            <div className="form-field"><label className="field-label">Manager / Reporting To</label><input className="doc-input" placeholder="Manager Name" value={form.managerName} onChange={e => updateField("managerName", e.target.value)} /></div>
            <div className="form-field"><label className="field-label">Manager Designation</label><input className="doc-input" placeholder="Team Lead / HR Manager" value={form.managerDesignation} onChange={e => updateField("managerDesignation", e.target.value)} /></div>
            <div className="form-field"><label className="field-label">Company Name</label><input className="doc-input" placeholder="Company Pvt. Ltd." value={form.companyName} onChange={e => updateField("companyName", e.target.value)} /></div>
            <div style={{ borderTop: "1px solid #F3F4F6", margin: "16px 0" }} />
            <p className="form-label">Resignation Details</p>
            <div className="form-row">
              <div className="form-field" style={{ marginBottom: 0 }}><label className="field-label">Letter Date</label><input className="doc-input" type="date" value={form.letterDate} onChange={e => updateField("letterDate", e.target.value)} /></div>
              <div className="form-field" style={{ marginBottom: 0 }}><label className="field-label">Last Working Day</label><input className="doc-input" type="date" value={form.lastWorkingDate} onChange={e => updateField("lastWorkingDate", e.target.value)} /></div>
            </div>
            <div className="form-field" style={{ marginTop: "10px" }}>
              <label className="field-label">Notice Period (days)</label>
              <select className="doc-select" value={form.noticePeriod} onChange={e => updateField("noticePeriod", e.target.value)}>
                {["7", "14", "30", "60", "90"].map(d => <option key={d} value={d}>{d} days</option>)}
              </select>
            </div>
            <div style={{ borderTop: "1px solid #F3F4F6", margin: "16px 0" }} />
            <p className="form-label">Reason</p>
            <div style={{ display: "flex", flexDirection: "column", gap: "6px", marginBottom: "10px" }}>
              {[
                { v: "personal", l: "New Opportunity" },
                { v: "relocation", l: "Relocation" },
                { v: "health", l: "Health Reasons" },
                { v: "higher", l: "Higher Education" },
                { v: "custom", l: "Custom Reason" },
              ].map(opt => (
                <button key={opt.v} onClick={() => updateField("reason", opt.v)}
                  className={`toggle-btn ${form.reason === opt.v ? "active" : ""}`}
                  style={{ justifyContent: "flex-start" }}>
                  {opt.l}
                </button>
              ))}
            </div>
            {form.reason === "custom" && (
              <div className="form-field">
                <label className="field-label">Custom Reason</label>
                <textarea className="doc-textarea" style={{ minHeight: "80px" }}
                  placeholder="Write your reason here..."
                  value={form.customReason}
                  onChange={e => updateField("customReason", e.target.value)}
                />
              </div>
            )}
            <div className="form-field">
              <label className="field-label">Gratitude Note (optional)</label>
              <textarea className="doc-textarea" style={{ minHeight: "70px" }}
                placeholder="Express gratitude to the company..."
                value={form.gratitudeNote}
                onChange={e => updateField("gratitudeNote", e.target.value)}
              />
            </div>
            <button onClick={handleDownload} disabled={downloading} className="download-pdf-btn">

              <Download size={15} />

              {downloading ? "Generating..." : "Download PDF"}

            </button>
          </div>

          <div className="preview-panel">
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "16px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "6px" }}>
                <Eye size={14} color="#9CA3AF" />
                <span style={{ fontSize: "12px", color: "#9CA3AF", fontFamily: "Inter, sans-serif", fontWeight: 600 }}>LIVE PREVIEW</span>
              </div>
              <button onClick={handleDownload} disabled={downloading} className="download-pdf-btn">

                <Download size={15} />

                {downloading ? "Generating..." : "Download PDF"}

              </button>
            </div>
            <ResignationPreview form={form} />
          </div>
        </div>
        <div style={{ maxWidth: "1300px", margin: "0 auto", padding: "0 24px 40px" }}>
          <AdSense adSlot="SLOT_ID_RESIGN" />
        </div>
      </div>
      <Footer />
    </>
  );
}