import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/theme/app_theme.dart';
import '../../../../core/utils/indian_states.dart';
import '../../data/models/invoice_form.dart';
import '../providers/invoice_provider.dart';

/// Live preview — renders the selected template matching the web design.
class InvoicePreviewWidget extends ConsumerWidget {
  const InvoicePreviewWidget({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final form = ref.watch(invoiceFormProvider);
    final accent = _hexColor(form.templateColor);

    final content = switch (form.templateName) {
      'Minimal'   => _MinimalTemplate(form: form, accent: accent),
      'Modern'    => _ModernTemplate(form: form, accent: accent),
      'Corporate' => _CorporateTemplate(form: form, accent: accent),
      'Elegant'   => _ElegantTemplate(form: form, accent: accent),
      _           => _ClassicTemplate(form: form, accent: accent),
    };

    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(AppRadius.lg),
        border: Border.all(color: AppColors.border),
      ),
      clipBehavior: Clip.hardEdge,
      child: content,
    );
  }

  static Color _hexColor(String hex) => Color(
        int.parse('0xFF${hex.startsWith('#') ? hex.substring(1) : hex}'),
      );
}

// ─── Shared helpers ───────────────────────────────────────────────────────────

String _taxLabel(TaxType t) => switch (t) {
      TaxType.cgstSgst => 'CGST + SGST',
      TaxType.igst => 'IGST',
      TaxType.none => 'No Tax',
    };

String _stateName(String code) =>
    IndianStates.nameFromCode(code).isEmpty ? '' : IndianStates.nameFromCode(code);

Widget _label(String text, {Color? color}) => Text(
      text.toUpperCase(),
      style: TextStyle(
        fontFamily: 'Inter',
        fontSize: 7,
        fontWeight: FontWeight.w700,
        letterSpacing: 0.8,
        color: color ?? AppColors.textLight,
      ),
    );

Widget _value(String text, {Color? color, bool bold = false, double size = 10}) => Text(
      text,
      style: TextStyle(
        fontFamily: 'Inter',
        fontSize: size,
        fontWeight: bold ? FontWeight.w700 : FontWeight.w400,
        color: color ?? AppColors.textPrimary,
      ),
    );

Widget _footerText() => Center(
      child: Text(
        'Generated by DocMinty.com',
        style: const TextStyle(fontSize: 8, color: AppColors.textLight, fontFamily: 'Inter'),
      ),
    );

// ─── Shared items table (used by Classic / Corporate / Elegant) ───────────────

class _ItemsTable extends StatelessWidget {
  const _ItemsTable({required this.form, required this.accent, this.headerBg, this.rowBorderColor});
  final InvoiceForm form;
  final Color accent;
  final Color? headerBg;
  final Color? rowBorderColor;

  @override
  Widget build(BuildContext context) {
    return Table(
      columnWidths: {
        0: const FixedColumnWidth(20),
        1: const FlexColumnWidth(3),
        if (form.showHsn) 2: const FlexColumnWidth(1.5),
        3: const FixedColumnWidth(28),
        4: const FlexColumnWidth(1.5),
        5: const FixedColumnWidth(32),
        6: const FlexColumnWidth(1.8),
      },
      children: [
        TableRow(
          decoration: BoxDecoration(color: headerBg ?? const Color(0xFFF0F4F3)),
          children: [
            _th('#'), _th('DESCRIPTION'),
            if (form.showHsn) _th('HSN'),
            _th('QTY'), _th('RATE'), _th('GST%'), _th('AMOUNT'),
          ],
        ),
        ...form.items.asMap().entries.map((e) {
          final item = e.value;
          return TableRow(
            decoration: BoxDecoration(
              border: Border(bottom: BorderSide(color: rowBorderColor ?? AppColors.borderLight)),
            ),
            children: [
              _td('${e.key + 1}'),
              _td(item.description.isEmpty ? '—' : item.description),
              if (form.showHsn) _td(item.hsn.isEmpty ? '—' : item.hsn),
              _td(item.qty),
              _td('Rs.${item.rateNum.toStringAsFixed(2)}'),
              _td('${item.gstRate}%'),
              _td('Rs.${item.totalAmount.toStringAsFixed(2)}', bold: true),
            ],
          );
        }),
      ],
    );
  }

  Widget _th(String t) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 5, horizontal: 3),
        child: Text(t, style: const TextStyle(fontSize: 7, fontFamily: 'Inter', fontWeight: FontWeight.w700, color: Color(0xFF6B7280))),
      );

  Widget _td(String t, {bool bold = false}) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 5, horizontal: 3),
        child: Text(t, style: TextStyle(fontSize: 8, fontFamily: 'Inter', fontWeight: bold ? FontWeight.w700 : FontWeight.w400, color: const Color(0xFF374151))),
      );
}

// Modern template uses a simplified items table with flex layout
class _ModernItemsTable extends StatelessWidget {
  const _ModernItemsTable({required this.form, required this.accent});
  final InvoiceForm form;
  final Color accent;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          color: accent,
          padding: const EdgeInsets.symmetric(vertical: 5, horizontal: 6),
          child: Row(children: [
            SizedBox(width: 20, child: _th('#')),
            Expanded(flex: 3, child: _th('DESCRIPTION')),
            SizedBox(width: 28, child: _th('QTY')),
            Expanded(flex: 2, child: _th('RATE')),
            Expanded(flex: 2, child: _th('AMOUNT')),
          ]),
        ),
        ...form.items.asMap().entries.map((e) {
          final item = e.value;
          return Container(
            padding: const EdgeInsets.symmetric(vertical: 5, horizontal: 6),
            decoration: const BoxDecoration(border: Border(bottom: BorderSide(color: Color(0xFFF3F4F6)))),
            child: Row(children: [
              SizedBox(width: 20, child: _td('${e.key + 1}')),
              Expanded(flex: 3, child: _td(item.description.isEmpty ? '—' : item.description)),
              SizedBox(width: 28, child: _td(item.qty)),
              Expanded(flex: 2, child: _td('Rs.${item.rateNum.toStringAsFixed(2)}')),
              Expanded(flex: 2, child: _td('Rs.${item.totalAmount.toStringAsFixed(2)}', bold: true)),
            ]),
          );
        }),
      ],
    );
  }

  Widget _th(String t) => Text(t, style: const TextStyle(fontSize: 7, fontFamily: 'Inter', fontWeight: FontWeight.w700, color: Colors.white));
  Widget _td(String t, {bool bold = false}) => Text(t, style: TextStyle(fontSize: 8, fontFamily: 'Inter', fontWeight: bold ? FontWeight.w700 : FontWeight.w400, color: const Color(0xFF374151)));
}

// Shared totals block
class _TotalsBlock extends StatelessWidget {
  const _TotalsBlock({required this.form, required this.accent, this.totalBg, this.totalFinalBg});
  final InvoiceForm form;
  final Color accent;
  final Color? totalBg;
  final Color? totalFinalBg;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.end,
      children: [
        _row('Subtotal', form.subtotal),
        if (form.taxType == TaxType.cgstSgst) ...[
          _row('CGST', form.cgst),
          _row('SGST', form.sgst),
        ] else if (form.taxType == TaxType.igst)
          _row('IGST', form.igst),
        const SizedBox(height: 4),
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 6),
          decoration: BoxDecoration(
            color: totalFinalBg ?? accent.withOpacity(0.08),
            borderRadius: BorderRadius.circular(3),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text('Total', style: TextStyle(fontSize: 11, fontFamily: 'Inter', fontWeight: FontWeight.w700, color: accent)),
              const SizedBox(width: 16),
              Text('Rs. ${form.grandTotal.toStringAsFixed(2)}', style: TextStyle(fontSize: 11, fontFamily: 'Inter', fontWeight: FontWeight.w700, color: accent)),
            ],
          ),
        ),
      ],
    );
  }

  Widget _row(String label, double amt) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 3),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(label, style: const TextStyle(fontSize: 9, fontFamily: 'Inter', color: Color(0xFF6B7280))),
            const SizedBox(width: 16),
            SizedBox(
              width: 80,
              child: Text('Rs. ${amt.toStringAsFixed(2)}', textAlign: TextAlign.right,
                  style: const TextStyle(fontSize: 9, fontFamily: 'Inter', color: Color(0xFF374151))),
            ),
          ],
        ),
      );
}

// ─── CLASSIC Template ─────────────────────────────────────────────────────────
// Web: white header, border-bottom accent, "INVOICE" in accent color top-right

class _ClassicTemplate extends StatelessWidget {
  const _ClassicTemplate({required this.form, required this.accent});
  final InvoiceForm form;
  final Color accent;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                Text(form.fromName.isEmpty ? 'Your Business' : form.fromName,
                    style: const TextStyle(fontSize: 14, fontFamily: 'SpaceGrotesk', fontWeight: FontWeight.w800, color: Color(0xFF111827))),
                if (form.fromGstin.isNotEmpty)
                  Text('GSTIN: ${form.fromGstin}', style: const TextStyle(fontSize: 8, color: Color(0xFF6B7280), fontFamily: 'Inter')),
                if (form.fromAddress.isNotEmpty)
                  Text(form.fromAddress, style: const TextStyle(fontSize: 8, color: Color(0xFF6B7280), fontFamily: 'Inter')),
                if (form.fromCity.isNotEmpty)
                  Text('${form.fromCity}, ${_stateName(form.fromState)}', style: const TextStyle(fontSize: 8, color: Color(0xFF6B7280), fontFamily: 'Inter')),
              ]),
              Column(crossAxisAlignment: CrossAxisAlignment.end, children: [
                Text('INVOICE', style: TextStyle(fontSize: 22, fontFamily: 'SpaceGrotesk', fontWeight: FontWeight.w800, color: accent)),
                Text('#${form.invoiceNumber}', style: const TextStyle(fontSize: 9, color: Color(0xFF6B7280), fontFamily: 'Inter')),
                if (form.invoiceDate.isNotEmpty)
                  Text('Date: ${form.invoiceDate}', style: const TextStyle(fontSize: 8, color: Color(0xFF9CA3AF), fontFamily: 'Inter')),
                if (form.dueDate.isNotEmpty)
                  Text('Due: ${form.dueDate}', style: const TextStyle(fontSize: 8, color: Color(0xFF9CA3AF), fontFamily: 'Inter')),
              ]),
            ],
          ),
          const SizedBox(height: 12),
          Divider(thickness: 2, color: accent, height: 2),
          const SizedBox(height: 12),

          // Bill To + Tax Type
          Row(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
            Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              _label('Bill To'),
              const SizedBox(height: 2),
              _value(form.toName.isEmpty ? 'Client' : form.toName, bold: true, size: 11),
              if (form.toGstin.isNotEmpty) _value('GSTIN: ${form.toGstin}', size: 8, color: const Color(0xFF6B7280)),
              if (form.toAddress.isNotEmpty) _value(form.toAddress, size: 8, color: const Color(0xFF6B7280)),
              if (form.toCity.isNotEmpty) _value('${form.toCity}, ${_stateName(form.toState)}', size: 8, color: const Color(0xFF6B7280)),
            ]),
            Column(crossAxisAlignment: CrossAxisAlignment.end, children: [
              _label('Tax Type'),
              const SizedBox(height: 2),
              _value(_taxLabel(form.taxType), size: 9),
            ]),
          ]),
          const SizedBox(height: 12),

          // Items
          _ItemsTable(form: form, accent: accent),
          const SizedBox(height: 10),

          // Totals
          Align(alignment: Alignment.centerRight, child: _TotalsBlock(form: form, accent: accent)),
          const SizedBox(height: 12),

          // Notes / Terms
          if (form.notes.isNotEmpty || form.terms.isNotEmpty) ...[
            const Divider(),
            if (form.notes.isNotEmpty) ...[
              const SizedBox(height: 6),
              _label('Notes'),
              Text(form.notes, style: const TextStyle(fontSize: 8, fontFamily: 'Inter', color: Color(0xFF6B7280))),
            ],
            if (form.terms.isNotEmpty) ...[
              const SizedBox(height: 6),
              _label('Terms & Conditions'),
              Text(form.terms, style: const TextStyle(fontSize: 8, fontFamily: 'Inter', color: Color(0xFF6B7280))),
            ],
          ],
          const SizedBox(height: 12),
          _footerText(),
        ],
      ),
    );
  }
}

// ─── MINIMAL Template ─────────────────────────────────────────────────────────
// Web: white bg, business name dark left, "Invoice" in accent right, thin divider

class _MinimalTemplate extends StatelessWidget {
  const _MinimalTemplate({required this.form, required this.accent});
  final InvoiceForm form;
  final Color accent;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [
            Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              Text(form.fromName.isEmpty ? 'Your Business' : form.fromName,
                  style: const TextStyle(fontSize: 12, fontFamily: 'SpaceGrotesk', fontWeight: FontWeight.w800, color: Color(0xFF111827))),
              if (form.fromGstin.isNotEmpty)
                Text('GSTIN: ${form.fromGstin}', style: const TextStyle(fontSize: 8, color: Color(0xFF9CA3AF), fontFamily: 'Inter')),
              if (form.fromCity.isNotEmpty)
                Text('${form.fromCity}, ${_stateName(form.fromState)}', style: const TextStyle(fontSize: 8, color: Color(0xFF9CA3AF), fontFamily: 'Inter')),
            ]),
            Column(crossAxisAlignment: CrossAxisAlignment.end, children: [
              Text('Invoice', style: TextStyle(fontSize: 20, fontFamily: 'SpaceGrotesk', fontWeight: FontWeight.w800, color: accent)),
              Text('#${form.invoiceNumber}', style: const TextStyle(fontSize: 9, color: Color(0xFF9CA3AF), fontFamily: 'Inter')),
              if (form.invoiceDate.isNotEmpty)
                Text('Date: ${form.invoiceDate}', style: const TextStyle(fontSize: 8, color: Color(0xFF9CA3AF), fontFamily: 'Inter')),
            ]),
          ]),
          const SizedBox(height: 14),
          Divider(thickness: 1.5, color: accent, height: 1.5),
          const SizedBox(height: 14),

          // Bill To + Tax Type
          Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [
            Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              _label('Bill To', color: const Color(0xFF9CA3AF)),
              const SizedBox(height: 3),
              _value(form.toName.isEmpty ? 'Client' : form.toName, bold: true, size: 11),
              if (form.toGstin.isNotEmpty) _value('GSTIN: ${form.toGstin}', size: 8, color: const Color(0xFF9CA3AF)),
              if (form.toCity.isNotEmpty) _value('${form.toCity}, ${_stateName(form.toState)}', size: 8, color: const Color(0xFF9CA3AF)),
            ]),
            Column(crossAxisAlignment: CrossAxisAlignment.end, children: [
              _label('Tax Type', color: const Color(0xFF9CA3AF)),
              const SizedBox(height: 3),
              _value(_taxLabel(form.taxType), size: 9),
            ]),
          ]),
          const SizedBox(height: 14),

          // Items table — only bottom border on header, accent colored
          _MinimalItemsTable(form: form, accent: accent),
          const SizedBox(height: 10),

          // Totals (clean, no bg)
          Align(alignment: Alignment.centerRight, child: _MinimalTotals(form: form, accent: accent)),
          const SizedBox(height: 16),

          // Footer
          Divider(thickness: 1, color: const Color(0xFFE5E7EB)),
          const SizedBox(height: 6),
          Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
            _footerText(),
            Text('Authorised Signatory', style: const TextStyle(fontSize: 7, color: Color(0xFF9CA3AF), fontFamily: 'Inter')),
          ]),
        ],
      ),
    );
  }
}

class _MinimalItemsTable extends StatelessWidget {
  const _MinimalItemsTable({required this.form, required this.accent});
  final InvoiceForm form;
  final Color accent;

  @override
  Widget build(BuildContext context) {
    return Table(
      columnWidths: {
        0: const FixedColumnWidth(20),
        1: const FlexColumnWidth(3),
        2: const FixedColumnWidth(28),
        3: const FlexColumnWidth(1.5),
        4: const FixedColumnWidth(32),
        5: const FlexColumnWidth(1.8),
      },
      children: [
        TableRow(
          decoration: BoxDecoration(border: Border(bottom: BorderSide(color: accent, width: 1.5))),
          children: [
            _th('#'), _th('DESCRIPTION'), _th('QTY'), _th('RATE'), _th('GST%'), _th('AMOUNT'),
          ],
        ),
        ...form.items.asMap().entries.map((e) {
          final item = e.value;
          return TableRow(
            decoration: const BoxDecoration(border: Border(bottom: BorderSide(color: Color(0xFFF3F4F6)))),
            children: [
              _td('${e.key + 1}'),
              _td(item.description.isEmpty ? '—' : item.description),
              _td(item.qty),
              _td('Rs.${item.rateNum.toStringAsFixed(2)}'),
              _td('${item.gstRate}%'),
              _td('Rs.${item.totalAmount.toStringAsFixed(2)}', bold: true),
            ],
          );
        }),
      ],
    );
  }

  Widget _th(String t) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 5, horizontal: 3),
        child: Text(t, style: TextStyle(fontSize: 7, fontFamily: 'Inter', fontWeight: FontWeight.w700, color: accent, letterSpacing: 0.5)),
      );
  Widget _td(String t, {bool bold = false}) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 5, horizontal: 3),
        child: Text(t, style: TextStyle(fontSize: 8, fontFamily: 'Inter', fontWeight: bold ? FontWeight.w700 : FontWeight.w400, color: const Color(0xFF374151))),
      );
}

class _MinimalTotals extends StatelessWidget {
  const _MinimalTotals({required this.form, required this.accent});
  final InvoiceForm form;
  final Color accent;

  @override
  Widget build(BuildContext context) {
    return Column(crossAxisAlignment: CrossAxisAlignment.end, children: [
      _row('Subtotal', form.subtotal),
      if (form.taxType == TaxType.cgstSgst) ...[
        _row('CGST', form.cgst),
        _row('SGST', form.sgst),
      ] else if (form.taxType == TaxType.igst)
        _row('IGST', form.igst),
      const SizedBox(height: 4),
      Divider(thickness: 1.5, color: accent),
      Row(mainAxisSize: MainAxisSize.min, children: [
        Text('Total', style: TextStyle(fontSize: 11, fontFamily: 'SpaceGrotesk', fontWeight: FontWeight.w700, color: accent)),
        const SizedBox(width: 16),
        Text('Rs. ${form.grandTotal.toStringAsFixed(2)}',
            style: TextStyle(fontSize: 11, fontFamily: 'SpaceGrotesk', fontWeight: FontWeight.w700, color: accent)),
      ]),
    ]);
  }

  Widget _row(String label, double amt) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 2),
        child: Row(mainAxisSize: MainAxisSize.min, children: [
          Text(label, style: const TextStyle(fontSize: 9, fontFamily: 'Inter', color: Color(0xFF9CA3AF))),
          const SizedBox(width: 16),
          SizedBox(
            width: 80,
            child: Text('Rs. ${amt.toStringAsFixed(2)}', textAlign: TextAlign.right,
                style: const TextStyle(fontSize: 9, fontFamily: 'Inter', color: Color(0xFF374151))),
          ),
        ]),
      );
}

// ─── MODERN Template ─────────────────────────────────────────────────────────
// Web: left sidebar in accent color, main content right

class _ModernTemplate extends StatelessWidget {
  const _ModernTemplate({required this.form, required this.accent});
  final InvoiceForm form;
  final Color accent;

  @override
  Widget build(BuildContext context) {
    return IntrinsicHeight(
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Left sidebar
          Container(
            width: 100,
            color: accent,
            padding: const EdgeInsets.all(12),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('INVOICE', style: const TextStyle(fontSize: 14, fontFamily: 'SpaceGrotesk', fontWeight: FontWeight.w800, color: Colors.white, height: 1.2)),
                const SizedBox(height: 4),
                Text('#${form.invoiceNumber}', style: const TextStyle(fontSize: 8, color: Colors.white70, fontFamily: 'Inter')),
                if (form.invoiceDate.isNotEmpty)
                  Text('Date: ${form.invoiceDate}', style: const TextStyle(fontSize: 7, color: Colors.white60, fontFamily: 'Inter')),
                if (form.dueDate.isNotEmpty)
                  Text('Due: ${form.dueDate}', style: const TextStyle(fontSize: 7, color: Colors.white60, fontFamily: 'Inter')),
                const SizedBox(height: 16),
                Text('BILL TO', style: const TextStyle(fontSize: 6, color: Colors.white54, fontFamily: 'Inter', fontWeight: FontWeight.w700, letterSpacing: 0.8)),
                const SizedBox(height: 3),
                Text(form.toName.isEmpty ? 'Client' : form.toName, style: const TextStyle(fontSize: 9, color: Colors.white, fontFamily: 'Inter', fontWeight: FontWeight.w700)),
                if (form.toGstin.isNotEmpty) Text('GSTIN: ${form.toGstin}', style: const TextStyle(fontSize: 7, color: Colors.white70, fontFamily: 'Inter')),
                if (form.toCity.isNotEmpty) Text(_stateName(form.toState), style: const TextStyle(fontSize: 7, color: Colors.white70, fontFamily: 'Inter')),
                const SizedBox(height: 12),
                Text('TAX TYPE', style: const TextStyle(fontSize: 6, color: Colors.white54, fontFamily: 'Inter', fontWeight: FontWeight.w700, letterSpacing: 0.8)),
                const SizedBox(height: 3),
                Text(_taxLabel(form.taxType), style: const TextStyle(fontSize: 8, color: Colors.white, fontFamily: 'Inter')),
              ],
            ),
          ),

          // Main content
          Expanded(
            child: Padding(
              padding: const EdgeInsets.all(12),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(form.fromName.isEmpty ? 'Your Business' : form.fromName,
                      style: const TextStyle(fontSize: 13, fontFamily: 'SpaceGrotesk', fontWeight: FontWeight.w700, color: Color(0xFF111827))),
                  if (form.fromGstin.isNotEmpty)
                    Text('GSTIN: ${form.fromGstin}', style: const TextStyle(fontSize: 7, color: Color(0xFF6B7280), fontFamily: 'Inter')),
                  if (form.fromAddress.isNotEmpty)
                    Text(form.fromAddress, style: const TextStyle(fontSize: 7, color: Color(0xFF6B7280), fontFamily: 'Inter')),
                  if (form.fromCity.isNotEmpty)
                    Text('${form.fromCity}, ${_stateName(form.fromState)}', style: const TextStyle(fontSize: 7, color: Color(0xFF6B7280), fontFamily: 'Inter')),
                  const SizedBox(height: 12),

                  // Items
                  _ModernItemsTable(form: form, accent: accent),
                  const SizedBox(height: 8),

                  // Totals
                  Align(alignment: Alignment.centerRight, child: _TotalsBlock(form: form, accent: accent)),
                  const SizedBox(height: 12),

                  // Footer
                  const Divider(thickness: 1, color: Color(0xFFE5E7EB)),
                  const SizedBox(height: 4),
                  _footerText(),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ─── CORPORATE Template ───────────────────────────────────────────────────────
// Web: top/bottom accent strips, centered header, formal style

class _CorporateTemplate extends StatelessWidget {
  const _CorporateTemplate({required this.form, required this.accent});
  final InvoiceForm form;
  final Color accent;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        // Top accent strip
        Container(height: 6, color: accent),

        // Centered header
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
          decoration: BoxDecoration(border: Border(bottom: BorderSide(color: accent, width: 2))),
          child: Column(children: [
            Text(form.fromName.isEmpty ? 'Your Business' : form.fromName,
                style: TextStyle(fontSize: 14, fontFamily: 'SpaceGrotesk', fontWeight: FontWeight.w800, color: accent), textAlign: TextAlign.center),
            Text('Official Tax Invoice',
                style: TextStyle(fontSize: 8, color: accent, fontFamily: 'Inter', letterSpacing: 1), textAlign: TextAlign.center),
            const SizedBox(height: 6),
            Row(mainAxisAlignment: MainAxisAlignment.center, children: [
              if (form.fromGstin.isNotEmpty) ...[
                Text('GSTIN: ${form.fromGstin}', style: const TextStyle(fontSize: 7, color: Color(0xFF6B7280), fontFamily: 'Inter')),
                const Text('  •  ', style: TextStyle(fontSize: 7, color: Color(0xFF6B7280))),
              ],
              Text('No: ${form.invoiceNumber}', style: const TextStyle(fontSize: 7, color: Color(0xFF6B7280), fontFamily: 'Inter')),
              if (form.invoiceDate.isNotEmpty) ...[
                const Text('  •  ', style: TextStyle(fontSize: 7, color: Color(0xFF6B7280))),
                Text('Date: ${form.invoiceDate}', style: const TextStyle(fontSize: 7, color: Color(0xFF6B7280), fontFamily: 'Inter')),
              ],
            ]),
          ]),
        ),

        // Body
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Bill To / Tax Type row (blue-tinted bg)
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                decoration: BoxDecoration(color: const Color(0xFFF8FAFD), borderRadius: BorderRadius.circular(4)),
                child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [
                  Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    _label('Bill To', color: accent),
                    const SizedBox(height: 2),
                    _value(form.toName.isEmpty ? 'Client' : form.toName, bold: true, size: 11),
                    if (form.toGstin.isNotEmpty) _value('GSTIN: ${form.toGstin}', size: 7, color: const Color(0xFF6B7280)),
                    if (form.toCity.isNotEmpty) _value('${form.toCity}, ${_stateName(form.toState)}', size: 7, color: const Color(0xFF6B7280)),
                  ]),
                  Column(crossAxisAlignment: CrossAxisAlignment.end, children: [
                    _label('Tax Type', color: accent),
                    const SizedBox(height: 2),
                    _value(_taxLabel(form.taxType), size: 9),
                  ]),
                ]),
              ),
              const SizedBox(height: 12),

              // Items table with full accent header
              _CorporateItemsTable(form: form, accent: accent),
              const SizedBox(height: 10),

              // Totals (white on final row)
              Align(alignment: Alignment.centerRight, child: _CorporateTotals(form: form, accent: accent)),
              const SizedBox(height: 12),

              // Footer
              Divider(thickness: 2, color: accent),
              const SizedBox(height: 4),
              Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
                _footerText(),
                Text('Authorised Signatory', style: const TextStyle(fontSize: 7, color: Color(0xFF9CA3AF), fontFamily: 'Inter')),
              ]),
            ],
          ),
        ),

        // Bottom accent strip
        Container(height: 6, color: accent),
      ],
    );
  }
}

class _CorporateItemsTable extends StatelessWidget {
  const _CorporateItemsTable({required this.form, required this.accent});
  final InvoiceForm form;
  final Color accent;

  @override
  Widget build(BuildContext context) {
    return Table(
      columnWidths: {
        0: const FixedColumnWidth(20),
        1: const FlexColumnWidth(3),
        2: const FixedColumnWidth(28),
        3: const FlexColumnWidth(1.5),
        4: const FixedColumnWidth(32),
        5: const FlexColumnWidth(1.8),
      },
      children: [
        TableRow(
          decoration: BoxDecoration(color: accent),
          children: [
            _th('#'), _th('DESCRIPTION'), _th('QTY'), _th('RATE'), _th('GST%'), _th('AMOUNT'),
          ],
        ),
        ...form.items.asMap().entries.map((e) {
          final item = e.value;
          final isEven = e.key % 2 == 0;
          return TableRow(
            decoration: BoxDecoration(
              color: isEven ? Colors.white : const Color(0xFFF8FAFD),
              border: const Border(bottom: BorderSide(color: Color(0xFFEBF0F7))),
            ),
            children: [
              _td('${e.key + 1}'),
              _td(item.description.isEmpty ? '—' : item.description),
              _td(item.qty),
              _td('Rs.${item.rateNum.toStringAsFixed(2)}'),
              _td('${item.gstRate}%'),
              _td('Rs.${item.totalAmount.toStringAsFixed(2)}', bold: true),
            ],
          );
        }),
      ],
    );
  }

  Widget _th(String t) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 5, horizontal: 3),
        child: Text(t, style: const TextStyle(fontSize: 7, fontFamily: 'Inter', fontWeight: FontWeight.w700, color: Colors.white, letterSpacing: 0.5)),
      );
  Widget _td(String t, {bool bold = false}) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 5, horizontal: 3),
        child: Text(t, style: TextStyle(fontSize: 8, fontFamily: 'Inter', fontWeight: bold ? FontWeight.w700 : FontWeight.w400, color: const Color(0xFF374151))),
      );
}

class _CorporateTotals extends StatelessWidget {
  const _CorporateTotals({required this.form, required this.accent});
  final InvoiceForm form;
  final Color accent;

  @override
  Widget build(BuildContext context) {
    return Column(crossAxisAlignment: CrossAxisAlignment.end, children: [
      _row('Subtotal', form.subtotal),
      if (form.taxType == TaxType.cgstSgst) ...[
        _row('CGST', form.cgst),
        _row('SGST', form.sgst),
      ] else if (form.taxType == TaxType.igst)
        _row('IGST', form.igst),
      const SizedBox(height: 4),
      Container(
        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 6),
        decoration: BoxDecoration(color: accent, borderRadius: BorderRadius.circular(3)),
        child: Row(mainAxisSize: MainAxisSize.min, children: [
          const Text('Total', style: TextStyle(fontSize: 11, fontFamily: 'Inter', fontWeight: FontWeight.w700, color: Colors.white)),
          const SizedBox(width: 16),
          Text('Rs. ${form.grandTotal.toStringAsFixed(2)}',
              style: const TextStyle(fontSize: 11, fontFamily: 'Inter', fontWeight: FontWeight.w700, color: Colors.white)),
        ]),
      ),
    ]);
  }

  Widget _row(String label, double amt) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 2),
        child: Row(mainAxisSize: MainAxisSize.min, children: [
          Text(label, style: const TextStyle(fontSize: 9, fontFamily: 'Inter', color: Color(0xFF6B7280))),
          const SizedBox(width: 16),
          SizedBox(
            width: 80,
            child: Text('Rs. ${amt.toStringAsFixed(2)}', textAlign: TextAlign.right,
                style: const TextStyle(fontSize: 9, fontFamily: 'Inter', color: Color(0xFF374151))),
          ),
        ]),
      );
}

// ─── ELEGANT Template ─────────────────────────────────────────────────────────
// Web: cream background, centered header, uppercase business name, accent borders

class _ElegantTemplate extends StatelessWidget {
  const _ElegantTemplate({required this.form, required this.accent});
  final InvoiceForm form;
  final Color accent;

  @override
  Widget build(BuildContext context) {
    return Container(
      color: const Color(0xFFFFFDF5),
      padding: const EdgeInsets.all(18),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Centered header
          Column(children: [
            Text(
              (form.fromName.isEmpty ? 'YOUR BUSINESS' : form.fromName).toUpperCase(),
              style: const TextStyle(fontSize: 15, fontFamily: 'SpaceGrotesk', fontWeight: FontWeight.w800, color: Color(0xFF111827), letterSpacing: 1),
              textAlign: TextAlign.center,
            ),
            if (form.fromGstin.isNotEmpty)
              Text('GSTIN: ${form.fromGstin}', style: const TextStyle(fontSize: 7, color: Color(0xFF6B7280), fontFamily: 'Inter'), textAlign: TextAlign.center),
            if (form.fromCity.isNotEmpty)
              Text('${form.fromCity}, ${_stateName(form.fromState)}', style: const TextStyle(fontSize: 7, color: Color(0xFF6B7280), fontFamily: 'Inter'), textAlign: TextAlign.center),
            const SizedBox(height: 8),
            Text('TAX INVOICE', style: TextStyle(fontSize: 9, color: accent, fontFamily: 'Inter', letterSpacing: 3, fontWeight: FontWeight.w600)),
            const SizedBox(height: 2),
            Text('#${form.invoiceNumber}${form.invoiceDate.isNotEmpty ? " • Date: ${form.invoiceDate}" : ""}',
                style: const TextStyle(fontSize: 8, color: Color(0xFF6B7280), fontFamily: 'Inter')),
          ]),
          const SizedBox(height: 14),
          Divider(thickness: 1, color: accent),
          const SizedBox(height: 12),

          // Bill To
          Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [
            Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              _label('Bill To', color: accent),
              const SizedBox(height: 3),
              _value(form.toName.isEmpty ? 'Client' : form.toName, bold: true, size: 11),
              if (form.toGstin.isNotEmpty) _value('GSTIN: ${form.toGstin}', size: 8, color: const Color(0xFF6B7280)),
              if (form.toCity.isNotEmpty) _value('${form.toCity}, ${_stateName(form.toState)}', size: 8, color: const Color(0xFF6B7280)),
            ]),
          ]),
          const SizedBox(height: 12),

          // Items table with accent-colored header labels, accent bottom border
          _ElegantItemsTable(form: form, accent: accent),
          const SizedBox(height: 10),

          // Totals (accent border, warm tinted bg)
          Align(alignment: Alignment.centerRight, child: _ElegantTotals(form: form, accent: accent)),

          // Notes / Terms
          if (form.notes.isNotEmpty || form.terms.isNotEmpty) ...[
            const SizedBox(height: 10),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
              decoration: BoxDecoration(
                color: accent.withOpacity(0.06),
                border: Border(left: BorderSide(color: accent, width: 3)),
              ),
              child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                if (form.notes.isNotEmpty) ...[
                  _label('Notes', color: accent),
                  Text(form.notes, style: const TextStyle(fontSize: 8, fontFamily: 'Inter', color: Color(0xFF6B7280))),
                ],
                if (form.terms.isNotEmpty) ...[
                  _label('Terms', color: accent),
                  Text(form.terms, style: const TextStyle(fontSize: 8, fontFamily: 'Inter', color: Color(0xFF6B7280))),
                ],
              ]),
            ),
          ],
          const SizedBox(height: 12),

          // Footer
          Divider(thickness: 2, color: accent),
          const SizedBox(height: 4),
          Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
            _footerText(),
            Text('Authorised Signatory', style: const TextStyle(fontSize: 7, color: Color(0xFF9CA3AF), fontFamily: 'Inter')),
          ]),
        ],
      ),
    );
  }
}

class _ElegantItemsTable extends StatelessWidget {
  const _ElegantItemsTable({required this.form, required this.accent});
  final InvoiceForm form;
  final Color accent;

  @override
  Widget build(BuildContext context) {
    return Table(
      columnWidths: {
        0: const FixedColumnWidth(20),
        1: const FlexColumnWidth(3),
        2: const FixedColumnWidth(28),
        3: const FlexColumnWidth(1.5),
        4: const FixedColumnWidth(32),
        5: const FlexColumnWidth(1.8),
      },
      children: [
        TableRow(
          decoration: BoxDecoration(border: Border(bottom: BorderSide(color: accent, width: 2))),
          children: [
            _th('#'), _th('DESCRIPTION'), _th('QTY'), _th('RATE'), _th('GST%'), _th('AMOUNT'),
          ],
        ),
        ...form.items.asMap().entries.map((e) {
          final item = e.value;
          return TableRow(
            decoration: const BoxDecoration(border: Border(bottom: BorderSide(color: Color(0xFFF5ECD5)))),
            children: [
              _td('${e.key + 1}'),
              _td(item.description.isEmpty ? '—' : item.description),
              _td(item.qty),
              _td('Rs.${item.rateNum.toStringAsFixed(2)}'),
              _td('${item.gstRate}%'),
              _td('Rs.${item.totalAmount.toStringAsFixed(2)}', bold: true),
            ],
          );
        }),
      ],
    );
  }

  Widget _th(String t) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 5, horizontal: 3),
        child: Text(t, style: TextStyle(fontSize: 7, fontFamily: 'Inter', fontWeight: FontWeight.w700, color: accent, letterSpacing: 0.5)),
      );
  Widget _td(String t, {bool bold = false}) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 5, horizontal: 3),
        child: Text(t, style: TextStyle(fontSize: 8, fontFamily: 'Inter', fontWeight: bold ? FontWeight.w700 : FontWeight.w400, color: const Color(0xFF374151))),
      );
}

class _ElegantTotals extends StatelessWidget {
  const _ElegantTotals({required this.form, required this.accent});
  final InvoiceForm form;
  final Color accent;

  @override
  Widget build(BuildContext context) {
    return Column(crossAxisAlignment: CrossAxisAlignment.end, children: [
      _row('Subtotal', form.subtotal),
      if (form.taxType == TaxType.cgstSgst) ...[
        _row('CGST', form.cgst),
        _row('SGST', form.sgst),
      ] else if (form.taxType == TaxType.igst)
        _row('IGST', form.igst),
      const SizedBox(height: 4),
      Container(
        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 6),
        decoration: BoxDecoration(
          color: accent.withOpacity(0.06),
          border: Border.all(color: accent, width: 1),
          borderRadius: BorderRadius.circular(3),
        ),
        child: Row(mainAxisSize: MainAxisSize.min, children: [
          Text('Total', style: TextStyle(fontSize: 11, fontFamily: 'SpaceGrotesk', fontWeight: FontWeight.w700, color: accent)),
          const SizedBox(width: 16),
          Text('Rs. ${form.grandTotal.toStringAsFixed(2)}',
              style: TextStyle(fontSize: 11, fontFamily: 'SpaceGrotesk', fontWeight: FontWeight.w700, color: accent)),
        ]),
      ),
    ]);
  }

  Widget _row(String label, double amt) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 2),
        child: Row(mainAxisSize: MainAxisSize.min, children: [
          Text(label, style: const TextStyle(fontSize: 9, fontFamily: 'Inter', color: Color(0xFF6B7280))),
          const SizedBox(width: 16),
          SizedBox(
            width: 80,
            child: Text('Rs. ${amt.toStringAsFixed(2)}', textAlign: TextAlign.right,
                style: const TextStyle(fontSize: 9, fontFamily: 'Inter', color: Color(0xFF374151))),
          ),
        ]),
      );
}
