"use client";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsPage() {
    return (
        <>
            <Navbar />
            <main style={{
                maxWidth: "720px", margin: "0 auto",
                padding: "64px 24px"
            }}>
                <h1 style={{
                    fontFamily: "Space Grotesk, sans-serif",
                    fontSize: "32px", fontWeight: 700,
                    color: "#111827", margin: "0 0 8px"
                }}>
                    Terms of Service
                </h1>
                <p style={{
                    fontSize: "13px", color: "#9CA3AF",
                    fontFamily: "Inter, sans-serif",
                    margin: "0 0 32px"
                }}>
                    Last updated: March 2026
                </p>
                {[
                    ["Use of Service",
                        "DocMinty provides document generation tools for Indian businesses. By using our service, you agree to use it only for lawful purposes."],
                    ["Free Tier",
                        "The free tier is available for individual use. Documents generated on the free tier include a 'Generated by DocMinty.com' footer."],
                    ["Pro Subscription",
                        "Pro subscriptions are billed monthly. You may cancel at any time. A 7-day money-back guarantee applies to all paid plans."],
                    ["Intellectual Property",
                        "The documents you create belong to you. DocMinty retains rights to its platform, templates, and technology."],
                    ["Limitation of Liability",
                        "DocMinty is not liable for any tax or legal compliance issues arising from documents generated on our platform. Always verify documents with a qualified professional."],
                    ["Contact",
                        "For terms enquiries, contact us at legal@docminty.com"],
                ].map(([title, body]) => (
                    <div key={title} style={{ marginBottom: "28px" }}>
                        <h2 style={{
                            fontFamily: "Space Grotesk, sans-serif",
                            fontSize: "18px", fontWeight: 700,
                            color: "#111827", margin: "0 0 8px"
                        }}>{title}</h2>
                        <p style={{
                            fontSize: "15px", color: "#374151",
                            fontFamily: "Inter, sans-serif",
                            lineHeight: 1.8, margin: 0
                        }}>{body}</p>
                    </div>
                ))}
            </main>
            <Footer />
        </>
    );
}