"use client";
import { useState, useRef, useEffect, useCallback } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AdSense from "@/components/AdSense";
import Link from "next/link";
import { Download, RefreshCw, Link as LinkIcon, QrCode, Copy, Check, LogIn, Image } from "lucide-react";
import QRCode from "qrcode";
import { getAccessToken, authApi, clearTokens } from "@/api/auth";
import { toast, Toaster } from "react-hot-toast";

const T = "#0D9488";

const PRESETS = [
  { label: "URL / Link",  placeholder: "https://docminty.com",                  prefix: "" },
  { label: "WhatsApp",    placeholder: "91XXXXXXXXXX",                          prefix: "https://wa.me/" },
  { label: "UPI Payment", placeholder: "upi://pay?pa=name@upi&pn=Name&am=100", prefix: "" },
  { label: "Email",       placeholder: "hello@example.com",                     prefix: "mailto:" },
  { label: "Phone",       placeholder: "9876543210",                            prefix: "tel:+" },
  { label: "Plain Text",  placeholder: "Enter any text...",                     prefix: "" },
];

const SIZES  = [128, 256, 512, 1024];
const COLORS = [
  { fg: "#0D9488", bg: "#FFFFFF", label: "Teal"     },
  { fg: "#111827", bg: "#FFFFFF", label: "Black"    },
  { fg: "#1E3A5F", bg: "#FFFFFF", label: "Navy"     },
  { fg: "#7C3AED", bg: "#FFFFFF", label: "Purple"   },
  { fg: "#DC2626", bg: "#FFFFFF", label: "Red"      },
  { fg: "#FFFFFF", bg: "#0D9488", label: "Inverted" },
];

const MAX_CHARS = { L: 2953, M: 2331, Q: 1663, H: 1273 };

export default function QRGeneratorPage() {
  const canvasRef    = useRef(null);
  const logoInputRef = useRef(null);
  const [user,        setUser]        = useState(null);
  const [authChecked, setAuthChecked] = useState(false);
  const [input,       setInput]       = useState("");
  const [preset,      setPreset]      = useState(0);
  const [size,        setSize]        = useState(256);
  const [colorIdx,    setColorIdx]    = useState(0);
  const [margin,      setMargin]      = useState(2);
  const [errorLevel,  setErrorLevel]  = useState("M");
  const [copied,      setCopied]      = useState(false);
  const [generated,   setGenerated]   = useState(false);
  const [centerLogo,  setCenterLogo]  = useState(null);
  const [qrError,     setQrError]     = useState("");
  const [showPreview, setShowPreview] = useState(false); // mobile toggle

  const isLoggedIn = !!user;
  const finalValue = input ? (PRESETS[preset].prefix + input) : "";
  const color      = COLORS[colorIdx];

  useEffect(() => {
    const token = getAccessToken();
    if (token) {
      authApi.me().then(res => setUser(res.data.data)).catch(() => {}).finally(() => setAuthChecked(true));
    } else { setAuthChecked(true); }
  }, []);

  const generateQR = useCallback(async () => {
    if (!finalValue || !canvasRef.current) return;
    try {
      setQrError("");
      const level = (isLoggedIn && centerLogo) ? "H" : errorLevel;
      if (finalValue.length > MAX_CHARS[level]) {
        setQrError("Text too long (" + finalValue.length + "/" + MAX_CHARS[level] + " chars). Try Low error correction or shorten the text.");
        setGenerated(false); return;
      }
      await QRCode.toCanvas(canvasRef.current, finalValue, {
        width: size, margin,
        errorCorrectionLevel: level,
        color: { dark: color.fg, light: color.bg },
      });
      const ctx = canvasRef.current.getContext("2d");
      if (isLoggedIn && centerLogo) {
        const img = new window.Image();
        img.onload = () => {
          const ls = size * 0.2, x = (size - ls) / 2, y = (size - ls) / 2;
          ctx.fillStyle = "#fff";
          ctx.beginPath();
          ctx.roundRect(x-6, y-6, ls+12, ls+12, 8);
          ctx.fill();
          ctx.drawImage(img, x, y, ls, ls);
        };
        img.src = centerLogo;
      }
      if (!isLoggedIn) {
        const brandH = 28;
        const qrData = ctx.getImageData(0, 0, size, size);
        canvasRef.current.height = size + brandH;
        ctx.putImageData(qrData, 0, 0);
        ctx.fillStyle = color.bg;
        ctx.fillRect(0, size, size, brandH);
        ctx.fillStyle = T;
        ctx.font = "bold 11px Inter, sans-serif";
        ctx.textAlign = "center";
        ctx.fillText("Generated by DocMinty.com", size / 2, size + 18);
      }
      setGenerated(true);
      setShowPreview(true); // auto-show preview on mobile after generate
    } catch (e) {
      setQrError("Could not generate QR. Please check your input.");
      setGenerated(false);
    }
  }, [finalValue, size, margin, errorLevel, color, isLoggedIn, centerLogo]);

  useEffect(() => {
    if (input && authChecked) generateQR();
    else { setGenerated(false); setQrError(""); }
  }, [input, preset, size, colorIdx, margin, errorLevel, centerLogo, authChecked, generateQR]);

  const downloadPNG = () => {
    if (!canvasRef.current || !generated) return;
    const a = document.createElement("a");
    a.download = `qr-${Date.now()}.png`;
    a.href = canvasRef.current.toDataURL("image/png");
    a.click();
    toast.success("Downloaded PNG");
  };

  const copyImage = async () => {
    if (!canvasRef.current || !generated) return;
    try {
      canvasRef.current.toBlob(async (blob) => {
        const item = new ClipboardItem({ "image/png": blob });
        await navigator.clipboard.write([item]);
        toast.success("Image copied to clipboard!");
      });
    } catch (err) {
      toast.error("Could not copy image");
    }
  };

  const shareQR = async () => {
    if (!canvasRef.current || !generated) return;
    try {
      canvasRef.current.toBlob(async (blob) => {
        const file = new File([blob], "qr.png", { type: "image/png" });
        if (navigator.share) {
          await navigator.share({
            files: [file],
            title: "My QR Code",
            text: "Generated via DocMinty",
          });
        } else {
          copyLink();
        }
      });
    } catch (err) {
      console.error(err);
    }
  };

  const downloadSVG = async () => {
    if (!finalValue || !isLoggedIn) return;
    try {
      const svg = await QRCode.toString(finalValue, { type:"svg", width:size, margin, errorCorrectionLevel:errorLevel, color:{dark:color.fg,light:color.bg} });
      const a = document.createElement("a");
      a.download = "qr.svg";
      a.href = URL.createObjectURL(new Blob([svg], { type:"image/svg+xml" }));
      a.click();
    } catch(e) { console.error(e); }
  };

  const copyLink = async () => {
    if (!finalValue) return;
    await navigator.clipboard.writeText(finalValue);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleLogoUpload = (e) => {
    const file = e.target.files?.[0]; if (!file) return;
    const r = new FileReader();
    r.onload = (ev) => setCenterLogo(ev.target.result);
    r.readAsDataURL(file);
  };

  return (
    <>
      <style>{`
        .qr-layout { display: grid; grid-template-columns: 1fr 360px; gap: 24px; align-items: start; }
        .qr-preview-sticky { position: sticky; top: 20px; }
        .qr-size-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 8px; }
        .qr-ec-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 8px; }
        .qr-preset-wrap { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 16px; }
        .qr-dl-row { display: flex; gap: 8px; margin-bottom: 8px; }
        .qr-compare-row { display: flex; }
        .qr-header-inner { display: flex; justify-content: space-between; align-items: center; }
        .qr-mobile-preview-btn { display: none; }
        @media (max-width: 768px) {
          .qr-layout { grid-template-columns: 1fr; gap: 16px; }
          .qr-preview-sticky { position: static; }
          .qr-size-grid { grid-template-columns: repeat(2,1fr); }
          .qr-ec-grid { grid-template-columns: repeat(2,1fr); }
          .qr-preset-wrap { gap: 6px; }
          .qr-mobile-preview-btn { display: flex; width: 100%; align-items: center; justify-content: center; gap: 8px; padding: 12px; background: #0D9488; color: #fff; border: none; border-radius: 10px; font-size: 14px; font-weight: 700; cursor: pointer; font-family: Space Grotesk, sans-serif; margin-bottom: 8px; }
          .qr-header-inner { flex-direction: column; align-items: flex-start; gap: 10px; }
          .qr-dl-row { flex-direction: column; }
        }
        @media (max-width: 480px) {
          .qr-size-grid { grid-template-columns: repeat(2,1fr); }
          .qr-color-wrap { display: flex; flex-wrap: wrap; gap: 6px; }
        }
      `}</style>

      <Navbar />
      <div style={{ background: "#F0F4F3", minHeight: "calc(100vh - 120px)" }}>

        {/* Header */}
        <div style={{ background: "#fff", borderBottom: "1px solid #E5E7EB", padding: "14px 24px" }}>
          <div style={{ maxWidth: "1100px", margin: "0 auto" }} className="qr-header-inner">
            <div>
              <h1 style={{ fontFamily: "Space Grotesk, sans-serif", fontSize: "18px", fontWeight: 700, margin: 0, color: "#111827" }}>QR Code Generator</h1>
              <p style={{ fontSize: "12px", color: "#9CA3AF", margin: "2px 0 0", fontFamily: "Inter, sans-serif" }}>Generate QR codes for URLs, WhatsApp, UPI, emails and more</p>
            </div>
            {!isLoggedIn && authChecked && (
              <Link href="/login" style={{ display:"flex", alignItems:"center", gap:"6px", padding:"8px 16px", background:T, color:"#fff", borderRadius:"8px", fontSize:"13px", fontWeight:700, textDecoration:"none", fontFamily:"Space Grotesk, sans-serif", whiteSpace:"nowrap" }}>
                <LogIn size={14} /> Sign in to remove branding
              </Link>
            )}
            {isLoggedIn && (
              <div style={{ display:"flex", alignItems:"center", gap:"8px", padding:"6px 14px", background:"#F0FDFA", border:"1px solid #99F6E4", borderRadius:"8px" }}>
                <div style={{ width:"8px", height:"8px", background:"#10B981", borderRadius:"50%" }} />
                <span style={{ fontSize:"12px", color:T, fontWeight:600, fontFamily:"Inter, sans-serif" }}>Clean QR — no branding</span>
              </div>
            )}
          </div>
        </div>

        <div style={{ maxWidth: "1100px", margin: "0 auto", padding: "20px 16px" }} className="qr-layout">

          {/* ── LEFT: Controls ── */}
          <div style={{ display:"flex", flexDirection:"column", gap:"16px" }}>

            {/* Guest banner */}
            {!isLoggedIn && authChecked && (
              <div style={{ background:"#FFFBEB", border:"1px solid #FDE68A", borderRadius:"10px", padding:"12px 16px", display:"flex", justifyContent:"space-between", alignItems:"center", gap:"12px", flexWrap:"wrap" }}>
                <div style={{ flex:1, minWidth:"200px" }}>
                  <p style={{ fontSize:"13px", fontWeight:700, color:"#92400E", margin:"0 0 2px", fontFamily:"Space Grotesk, sans-serif" }}>Free version — DocMinty branding on QR</p>
                  <p style={{ fontSize:"12px", color:"#B45309", margin:0, fontFamily:"Inter, sans-serif" }}>Sign in free to remove watermark, add your logo, download SVG.</p>
                </div>
                <Link href="/login" style={{ padding:"7px 16px", background:"#D97706", color:"#fff", borderRadius:"8px", fontSize:"12px", fontWeight:700, textDecoration:"none", fontFamily:"Space Grotesk, sans-serif", whiteSpace:"nowrap" }}>Sign In Free</Link>
              </div>
            )}

            {/* Mobile: show preview button when QR generated */}
            {generated && (
              <button className="qr-mobile-preview-btn" onClick={() => setShowPreview(!showPreview)}>
                <QrCode size={16} />
                {showPreview ? "Hide Preview" : "View QR Code"}
              </button>
            )}

            {/* Mobile inline preview */}
            {showPreview && generated && (
              <div style={{ display:"none" }} className="qr-mobile-inline">
                <style>{`.qr-mobile-inline { display: block !important; } @media(min-width:769px){.qr-mobile-inline{display:none!important}}`}</style>
                <div style={{ background:"#fff", border:"1px solid "+T, borderRadius:"12px", padding:"20px", textAlign:"center", boxShadow:"0 10px 30px -10px "+T+"33" }}>
                  <img src={canvasRef.current?.toDataURL()} style={{ maxWidth:"100%", borderRadius:"8px" }} alt="QR Draft" />
                  <p style={{ fontSize:"11px", color:T, fontWeight:600, margin:"12px 0 0", fontFamily:"Inter, sans-serif" }}>Live Mobile Preview</p>
                </div>
              </div>
            )}

            {/* Type Selector */}
            <div style={{ background:"#fff", border:"1px solid #E5E7EB", borderRadius:"12px", padding:"20px" }}>
              <p className="form-label">QR Code Type</p>
              <div className="qr-preset-wrap">
                {PRESETS.map((p,i) => (
                  <button key={i} onClick={() => { setPreset(i); setInput(""); }} style={{ padding:"6px 14px", borderRadius:"20px", border:"1px solid "+(preset===i?T:"#E5E7EB"), background:preset===i?"#F0FDFA":"#fff", color:preset===i?T:"#6B7280", fontSize:"12px", fontWeight:600, cursor:"pointer", fontFamily:"Inter, sans-serif" }}>{p.label}</button>
                ))}
              </div>
              <div className="form-field">
                <label className="field-label">{PRESETS[preset].label}{PRESETS[preset].prefix&&<span style={{fontSize:"11px",color:"#9CA3AF",marginLeft:"6px"}}>(prefix: {PRESETS[preset].prefix})</span>}</label>
                {preset===5 ? (
                  <textarea className="doc-textarea" style={{ minHeight:"80px" }} placeholder={PRESETS[preset].placeholder} value={input} onChange={e=>setInput(e.target.value)} />
                ) : (
                  <div style={{ position:"relative" }}>
                    <LinkIcon size={14} color="#9CA3AF" style={{ position:"absolute", left:"12px", top:"50%", transform:"translateY(-50%)" }} />
                    <input className="doc-input" style={{ paddingLeft:"36px" }} placeholder={PRESETS[preset].placeholder} value={input} onChange={e=>setInput(e.target.value)} />
                  </div>
                )}
                <p style={{ fontSize:"11px", color:finalValue.length>1000?"#EF4444":"#9CA3AF", margin:"4px 0 0", textAlign:"right", fontFamily:"Inter, sans-serif" }}>
                  {finalValue.length} chars {finalValue.length>1000?"(approaching limit)":""}
                </p>
              </div>
              {qrError && (
                <div style={{ background:"#FEF2F2", border:"1px solid #FECACA", borderRadius:"8px", padding:"10px 14px", marginTop:"8px" }}>
                  <p style={{ fontSize:"12px", color:"#DC2626", margin:0, fontFamily:"Inter, sans-serif" }}>{qrError}</p>
                </div>
              )}
              {finalValue && !qrError && (
                <div style={{ display:"flex", alignItems:"center", gap:"8px", padding:"8px 12px", background:"#F0FDFA", borderRadius:"8px", marginTop:"8px" }}>
                  <span style={{ fontSize:"11px", color:T, fontFamily:"monospace", flex:1, overflow:"hidden", textOverflow:"ellipsis", whiteSpace:"nowrap" }}>{finalValue}</span>
                  <button onClick={copyLink} style={{ background:"none", border:"none", cursor:"pointer", color:T, display:"flex", alignItems:"center", gap:"4px", fontSize:"11px", fontWeight:600, fontFamily:"Inter, sans-serif", flexShrink:0 }}>
                    {copied?<Check size={12}/>:<Copy size={12}/>}{copied?" Copied!":" Copy"}
                  </button>
                </div>
              )}
            </div>

            {/* Customization */}
            <div style={{ background:"#fff", border:"1px solid #E5E7EB", borderRadius:"12px", padding:"20px" }}>
              <p className="form-label">Customization</p>
              <div className="form-field">
                <label className="field-label">Size</label>
                <div className="qr-size-grid">
                  {SIZES.map(s => (
                    <button key={s} onClick={()=>setSize(s)} style={{ padding:"8px", borderRadius:"8px", border:"1px solid "+(size===s?T:"#E5E7EB"), background:size===s?"#F0FDFA":"#fff", color:size===s?T:"#6B7280", fontSize:"12px", fontWeight:600, cursor:"pointer", fontFamily:"Inter, sans-serif" }}>{s}px</button>
                  ))}
                </div>
              </div>
              <div className="form-field">
                <label className="field-label">Color Style</label>
                <div className="qr-color-wrap" style={{ display:"flex", gap:"8px", flexWrap:"wrap" }}>
                  {COLORS.map((c,i) => (
                    <button key={i} onClick={()=>setColorIdx(i)} style={{ padding:"6px 14px", borderRadius:"8px", border:"2px solid "+(colorIdx===i?c.fg:"#E5E7EB"), background:c.bg, color:c.fg, fontSize:"12px", fontWeight:700, cursor:"pointer", fontFamily:"Inter, sans-serif" }}>{c.label}</button>
                  ))}
                </div>
              </div>
              <div className="form-field">
                <label className="field-label">Error Correction <span style={{fontSize:"11px",color:"#9CA3AF"}}>(higher = more reliable)</span></label>
                <div className="qr-ec-grid">
                  {[["L","Low"],["M","Med"],["Q","High"],["H","Max"]].map(([val,lbl]) => (
                    <button key={val} onClick={()=>setErrorLevel(val)} style={{ padding:"8px", borderRadius:"8px", border:"1px solid "+(errorLevel===val?T:"#E5E7EB"), background:errorLevel===val?"#F0FDFA":"#fff", color:errorLevel===val?T:"#6B7280", fontSize:"12px", fontWeight:600, cursor:"pointer", fontFamily:"Inter, sans-serif" }}>{lbl}</button>
                  ))}
                </div>
              </div>
              <div className="form-field" style={{ marginBottom:0 }}>
                <label className="field-label">Quiet Zone (margin): {margin}</label>
                <input type="range" min={0} max={6} value={margin} onChange={e=>setMargin(Number(e.target.value))} style={{ width:"100%", accentColor:T }} />
              </div>
            </div>

            {/* Center Logo */}
            <div style={{ background:"#fff", border:"1px solid "+(isLoggedIn?"#E5E7EB":"#F3F4F6"), borderRadius:"12px", padding:"20px", opacity:isLoggedIn?1:0.65 }}>
              <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:"12px" }}>
                <p className="form-label" style={{ margin:0 }}>Center Logo</p>
                {!isLoggedIn&&<span style={{ fontSize:"11px", background:"#FEF9C3", color:"#D97706", padding:"2px 8px", borderRadius:"8px", fontWeight:700, fontFamily:"Space Grotesk, sans-serif" }}>LOGIN REQUIRED</span>}
              </div>
              {isLoggedIn ? (
                <div>
                  <p style={{ fontSize:"12px", color:"#6B7280", margin:"0 0 12px", fontFamily:"Inter, sans-serif" }}>Add your brand logo in the center of the QR code.</p>
                  <input ref={logoInputRef} type="file" accept="image/*" onChange={handleLogoUpload} style={{ display:"none" }} />
                  <div style={{ display:"flex", gap:"8px" }}>
                    <button onClick={()=>logoInputRef.current?.click()} style={{ flex:1, display:"flex", alignItems:"center", justifyContent:"center", gap:"6px", padding:"10px", border:"1px dashed "+T, borderRadius:"8px", background:"#F0FDFA", color:T, fontSize:"13px", fontWeight:600, cursor:"pointer", fontFamily:"Inter, sans-serif" }}>
                      <Image size={14} />{centerLogo?"Change Logo":"Upload Logo"}
                    </button>
                    {centerLogo&&<button onClick={()=>setCenterLogo(null)} style={{ padding:"10px 16px", border:"1px solid #FCA5A5", borderRadius:"8px", background:"#FEF2F2", color:"#EF4444", fontSize:"13px", fontWeight:600, cursor:"pointer", fontFamily:"Inter, sans-serif" }}>Remove</button>}
                  </div>
                  {centerLogo&&<p style={{ fontSize:"11px", color:T, margin:"6px 0 0", fontFamily:"Inter, sans-serif" }}>Logo added! Using Max error correction.</p>}
                </div>
              ) : (
                <div style={{ textAlign:"center", padding:"8px 0" }}>
                  <p style={{ fontSize:"12px", color:"#9CA3AF", margin:"0 0 8px", fontFamily:"Inter, sans-serif" }}>Place your brand logo in the center of the QR</p>
                  <Link href="/login" style={{ fontSize:"12px", fontWeight:700, color:T, textDecoration:"none", fontFamily:"Space Grotesk, sans-serif" }}>Sign in to unlock →</Link>
                </div>
              )}
            </div>
          </div>

          {/* ── RIGHT: Preview ── */}
          <div className="qr-preview-sticky" style={{ display:"flex", flexDirection:"column", gap:"16px" }}>
            <div style={{ background:"#fff", border:"1px solid #E5E7EB", borderRadius:"12px", padding:"24px", textAlign:"center" }}>
              <p style={{ fontSize:"12px", fontWeight:600, color:"#9CA3AF", fontFamily:"Inter, sans-serif", margin:"0 0 16px", textTransform:"uppercase", letterSpacing:"0.08em" }}>Live Preview</p>
              <div style={{ display:"flex", justifyContent:"center", alignItems:"center", minHeight:"180px" }}>
                {!generated && (
                  <div style={{ textAlign:"center" }}>
                    <QrCode size={56} color="#E5E7EB" style={{ margin:"0 auto 12px", display:"block" }} />
                    <p style={{ fontSize:"13px", color:"#9CA3AF", fontFamily:"Inter, sans-serif" }}>Enter a URL or text to generate</p>
                  </div>
                )}
                <canvas ref={canvasRef} style={{ display:generated?"block":"none", maxWidth:"100%", borderRadius:"8px" }} />
              </div>
              {!isLoggedIn&&generated&&(
                <div style={{ marginTop:"8px", padding:"5px 12px", background:"#F0FDFA", borderRadius:"6px", display:"inline-block" }}>
                  <span style={{ fontSize:"11px", color:T, fontWeight:600, fontFamily:"Space Grotesk, sans-serif" }}>Generated by DocMinty.com</span>
                </div>
              )}
              {generated && (
                <div style={{ marginTop:"16px" }}>
                  <button onClick={downloadPNG} style={{ width:"100%", display:"flex", alignItems:"center", justifyContent:"center", gap:"8px", padding:"12px", background:T, color:"#fff", border:"none", borderRadius:"10px", fontSize:"14px", fontWeight:700, cursor:"pointer", fontFamily:"Space Grotesk, sans-serif", marginBottom:"8px" }}>
                    <Download size={16}/> Download PNG
                  </button>
                  <div className="qr-dl-row">
                    <button onClick={copyImage} style={{ flex:1, display:"flex", alignItems:"center", justifyContent:"center", gap:"6px", padding:"10px", background:"#fff", color:T, border:"1px solid "+T, borderRadius:"8px", fontSize:"12px", fontWeight:700, cursor:"pointer", fontFamily:"Space Grotesk, sans-serif" }}>
                      <Copy size={13}/> Copy Image
                    </button>
                    {navigator.share ? (
                      <button onClick={shareQR} style={{ flex:1, display:"flex", alignItems:"center", justifyContent:"center", gap:"6px", padding:"10px", background:"#fff", color:T, border:"1px solid "+T, borderRadius:"8px", fontSize:"12px", fontWeight:700, cursor:"pointer", fontFamily:"Space Grotesk, sans-serif" }}>
                        <RefreshCw size={13}/> Share QR
                      </button>
                    ) : (
                      isLoggedIn && (
                        <button onClick={downloadSVG} style={{ flex:1, display:"flex", alignItems:"center", justifyContent:"center", gap:"6px", padding:"10px", background:"#fff", color:T, border:"1px solid "+T, borderRadius:"8px", fontSize:"12px", fontWeight:700, cursor:"pointer", fontFamily:"Space Grotesk, sans-serif" }}>
                          <Download size={13}/> Download SVG
                        </button>
                      )
                    )}
                  </div>
                  <button onClick={()=>{setInput("");setGenerated(false);setCenterLogo(null);setShowPreview(false);}} style={{ width:"100%", display:"flex", alignItems:"center", justifyContent:"center", gap:"6px", padding:"8px", background:"#F8F9FA", color:"#6B7280", border:"1px solid #E5E7EB", borderRadius:"8px", fontSize:"12px", fontWeight:600, cursor:"pointer", fontFamily:"Inter, sans-serif", marginTop:"8px" }}>
                    <RefreshCw size={12}/> Reset Generator
                  </button>
                </div>
              )}
            </div>

            {/* Feature comparison table */}
            <div style={{ background:"#fff", border:"1px solid #E5E7EB", borderRadius:"12px", overflow:"hidden" }}>
              <div style={{ padding:"12px 16px", background:"#F8F9FA", borderBottom:"1px solid #E5E7EB" }}>
                <p style={{ fontSize:"12px", fontWeight:700, color:"#111827", margin:0, fontFamily:"Space Grotesk, sans-serif" }}>Guest vs Signed In</p>
              </div>
              {[
                ["Generate QR codes",    true,  true ],
                ["Download PNG",         true,  true ],
                ["Download SVG",         false, true ],
                ["No branding",          false, true ],
                ["Add center logo",      false, true ],
              ].map(([feat,guest,loggedin],i) => (
                <div key={i} style={{ display:"flex", alignItems:"center", padding:"9px 16px", borderBottom:i<4?"1px solid #F3F4F6":"none", background:i%2===0?"#fff":"#FAFAFA" }}>
                  <span style={{ flex:1, fontSize:"12px", color:"#374151", fontFamily:"Inter, sans-serif" }}>{feat}</span>
                  <span style={{ width:"52px", textAlign:"center", fontSize:"13px", color:guest?"#10B981":"#D1D5DB" }}>{guest?"✓":"✗"}</span>
                  <span style={{ width:"52px", textAlign:"center", fontSize:"13px", color:loggedin?T:"#D1D5DB" }}>{loggedin?"✓":"✗"}</span>
                </div>
              ))}
              <div style={{ display:"flex", padding:"7px 16px", background:"#F8F9FA", borderTop:"1px solid #E5E7EB" }}>
                <span style={{ flex:1 }} />
                <span style={{ width:"52px", textAlign:"center", fontSize:"11px", color:"#9CA3AF", fontFamily:"Inter, sans-serif" }}>Guest</span>
                <span style={{ width:"52px", textAlign:"center", fontSize:"11px", color:T, fontWeight:700, fontFamily:"Inter, sans-serif" }}>Signed In</span>
              </div>
              {!isLoggedIn && (
                <div style={{ padding:"12px 16px", borderTop:"1px solid #E5E7EB" }}>
                  <Link href="/signup" style={{ display:"block", textAlign:"center", padding:"10px", background:T, color:"#fff", borderRadius:"8px", fontSize:"13px", fontWeight:700, textDecoration:"none", fontFamily:"Space Grotesk, sans-serif" }}>Create Free Account →</Link>
                </div>
              )}
            </div>
          </div>
        </div>

        <div style={{ maxWidth:"1100px", margin:"0 auto", padding:"0 16px 40px" }}>
          <AdSense adSlot="SLOT_ID_QR" />
        </div>
      </div>
      <Footer />
    </>
  );
}