# Server
server.port=8085
spring.application.name=docminty-backend

# MySQL Database Integration (VPS)
spring.datasource.url=jdbc:mysql://localhost:3306/docminty?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=docuser
spring.datasource.password=StrongPassword123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=docminty_jwt_secret_key_2026_must_be_256_bits_long_for_hs256_algorithm
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=docmintyofficial@gmail.com
spring.mail.password=amywfizsejcqlvfq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.debug=true
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

# Logging
logging.level.com.docminty.service.EmailService=DEBUG

# Razorpay
razorpay.key.id=rzp_test_SXmrLtIavlbCri
razorpay.key.secret=oLyPWsnjCDOUMtMI1RKQAtyD

# App
app.frontend.url=https://docminty.com
app.name=DocMinty
app.pro.monthly-price=19900
app.pro.annual-price=178800
app.enterprise.monthly-price=39900
app.enterprise.annual-price=358800
app.google.client-id=609432106453-46be6jvgqnpq0jd6cn6gqmq0bb65tcak.apps.googleusercontent.com

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cloudinary
cloudinary.cloud_name=db2vh8bst
cloudinary.api_key=162982254823585
cloudinary.api_secret=0QLhkddsa8hudkI78lcftynphZk
