import puppeteer from "puppeteer";
import { setCacheItem } from "@/lib/pdfCache";

export const runtime = "nodejs";
export const maxDuration = 60;

const HR_DOC_TYPES = new Set([
  "salary", "experience", "resignation", "job-offer",
  "proforma", "purchase", "packing", "voucher", "rent",
  "invoice", "quotation", "receipt",
  "certificate", "internship",
]);

// Certificate types render in landscape A4
const LANDSCAPE_DOC_TYPES = new Set(["certificate", "internship"]);

export async function POST(request) {
  try {
    const body = await request.json();
    const { docType, template, form, filename } = body;

    if (!HR_DOC_TYPES.has(docType)) {
      return Response.json({ error: "Unsupported document type" }, { status: 400 });
    }

    const isLandscape = LANDSCAPE_DOC_TYPES.has(docType);
    const token = crypto.randomUUID();
    setCacheItem(token, { docType, template, form });

    const host = request.headers.get("host") || "localhost:3000";
    const proto = request.headers.get("x-forwarded-proto") || "http";
    const baseUrl = `${proto}://${host}`;

    const browser = await puppeteer.launch({
      headless: "shell",
      pipe: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--font-render-hinting=none",
      ],
    });

    try {
      const page = await browser.newPage();

      // A4 portrait: 794×1123px | A4 landscape: 1123×794px at 96dpi
      await page.setViewport({
        width: isLandscape ? 1123 : 794,
        height: isLandscape ? 794 : 1123,
        deviceScaleFactor: 1,
      });

      await page.goto(`${baseUrl}/pdf-render/${token}`, {
        waitUntil: "networkidle0",
        timeout: 30000,
      });

      // Wait for preview to fully render (fonts + data)
      await page.waitForSelector("#pdf-ready", { timeout: 20000 });

      // Small buffer for any final paint
      await new Promise((r) => setTimeout(r, 200));

      // Hide the in-body "Generated by DocMinty.com" so it isn't duplicated
      // (Puppeteer footerTemplate renders it on every page instead)
      await page.evaluate(() => {
        document.querySelectorAll("p").forEach((p) => {
          if (p.textContent.trim() === "Generated by DocMinty.com") {
            p.style.display = "none";
          }
        });
      });

      const footerTemplate =
        '<div style="font-size:9px;color:#D1D5DB;font-family:sans-serif;' +
        'padding:0 0 6px 28px;width:100%;box-sizing:border-box;' +
        '-webkit-print-color-adjust:exact;">Generated by DocMinty.com</div>';

      const pdfBuffer = await page.pdf({
        format: "A4",
        landscape: isLandscape,
        printBackground: true,
        preferCSSPageSize: true,
        margin: { top: "0", right: "0", bottom: "20px", left: "0" },
        displayHeaderFooter: true,
        headerTemplate: "<span></span>",
        footerTemplate,
      });

      return new Response(pdfBuffer, {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="${(filename || "document.pdf").replace(/"/g, "")}"`,
          "Cache-Control": "no-store",
        },
      });
    } finally {
      await browser.close();
    }
  } catch (err) {
    console.error("[generate-hr-pdf] error:", err);
    return Response.json({ error: err.message }, { status: 500 });
  }
}
