"use client";
import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";

const REASONS = {
  personal: "I have decided to pursue a new opportunity that aligns more closely with my personal and professional goals.",
  relocation: "Due to relocation constraints, I am unable to continue in my current position.",
  health: "Due to personal health reasons, I am unable to continue in my current role.",
  higher: "I have been offered an opportunity to pursue higher education, which requires my full commitment.",
};

export default function ResignationClassicTemplate({ form }) {
  const T = form.templateColor || "#0D9488";
  
  const styles = StyleSheet.create({
    page: { fontFamily: "Helvetica", fontSize: 10, color: "#111827", padding: 40 },
    title: { fontSize: 18, fontFamily: "Helvetica-Bold", color: T, marginBottom: 4 },
    dateText: { fontSize: 9, color: "#9CA3AF", marginBottom: 20 },
    toName: { fontSize: 10, fontFamily: "Helvetica-Bold", color: "#374151", marginBottom: 2 },
    toSub: { fontSize: 9, color: "#6B7280", marginBottom: 16 },
    body: { fontSize: 10, color: "#374151", lineHeight: 1.8, marginBottom: 12 },
    signCol: { marginTop: 32, width: 160 },
    signImg: { height: 40, marginBottom: 5, objectFit: "contain" },
    signBox: { borderTopWidth: 1, borderTopColor: "#374151", paddingTop: 5 },
    signName: { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#111827" },
    signDesig: { fontSize: 9, color: "#6B7280", marginTop: 2 },
    footer: { marginTop: 20, paddingTop: 10, borderTopWidth: 1, borderTopColor: "#E5E7EB" },
    footerGen: { fontSize: 8, color: "#D1D5DB" },
  });

  const reasonText = form.reason === "custom" ? form.customReason : REASONS[form.reason] || "";
  const gratitude = form.gratitudeNote || "I am grateful for the opportunities for professional and personal development that you have provided during my tenure. I have enjoyed working with the team and value the experience I have gained here.";

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>RESIGNATION LETTER</Text>
        <Text style={styles.dateText}>{"Date: " + form.letterDate}</Text>
        <Text style={styles.toName}>{form.managerName || "Manager Name"}</Text>
        <Text style={styles.toSub}>{form.managerDesignation || "Designation"}{form.companyName ? ", " + form.companyName : ""}</Text>
        <Text style={styles.body}>{"Dear " + (form.managerName ? form.managerName.split(" ")[0] : "Sir/Madam") + ","}</Text>
        <Text style={styles.body}>
          {"I am writing to formally notify you of my resignation from the position of "}
          <Text style={{ fontFamily: "Helvetica-Bold" }}>{form.designation || "[Designation]"}</Text>
          {form.department ? " in the " + form.department + " department" : ""}
          {form.companyName ? " at " + form.companyName : ""}
          {". My last working day will be "}
          <Text style={{ color: T, fontFamily: "Helvetica-Bold" }}>{form.lastWorkingDate || "[Last Working Date]"}</Text>
          {", serving a notice period of " + (form.noticePeriod || "30") + " days."}
        </Text>
        {reasonText !== "" && <Text style={styles.body}>{reasonText}</Text>}
        <Text style={styles.body}>{gratitude}</Text>
        <Text style={styles.body}>I will ensure a smooth transition and will complete all pending tasks before my last working day. Please let me know how I can assist during this transition period.</Text>
        <Text style={styles.body}>Yours sincerely,</Text>
        <View style={styles.signCol}>
          {form.signature && <Image src={form.signature} style={styles.signImg} />}
          <View style={styles.signBox}>
            <Text style={styles.signName}>{form.employeeName || "Employee Name"}</Text>
            {form.designation && <Text style={styles.signDesig}>{form.designation}</Text>}
          </View>
        </View>
        <View style={styles.footer}>
          <Text style={styles.footerGen}>Generated by DocMinty.com</Text>
        </View>
      </Page>
    </Document>
  );
}
