"use client";
import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";

const REASONS = {
  personal: "I have decided to pursue a new opportunity that aligns more closely with my personal and professional goals.",
  relocation: "Due to relocation constraints, I am unable to continue in my current position.",
  health: "Due to personal health reasons, I am unable to continue in my current role.",
  higher: "I have been offered an opportunity to pursue higher education, which requires my full commitment.",
};

export default function ResignationElegantTemplate({ form }) {
  const T = form.templateColor || "#D97706";
  
  const styles = StyleSheet.create({
    page: { fontFamily: "Helvetica", fontSize: 10, color: "#111827", padding: "50 70", background: "#FFFDFA" },
    header: { marginBottom: 40, borderBottomWidth: 1, borderBottomColor: "#E5E7EB", paddingBottom: 20 },
    title: { fontSize: 24, fontFamily: "Helvetica-Bold", color: T, marginBottom: 8, letterSpacing: 1 },
    subtitle: { fontSize: 9, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: 2 },
    dateLine: { fontSize: 9, color: "#6B7280", marginBottom: 30, textAlign: "right" },
    toBox: { marginBottom: 30 },
    toName: { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#111827", marginBottom: 2 },
    toSub: { fontSize: 9, color: "#6B7280" },
    body: { fontSize: 10, color: "#374151", lineHeight: 2, marginBottom: 16 },
    highlight: { color: T, fontFamily: "Helvetica-Bold" },
    signImg: { height: 45, marginBottom: 5, objectFit: "contain" },
    signLine: { borderTopWidth: 1, borderTopColor: T, paddingTop: 8, width: 160 },
    signName: { fontSize: 12, fontFamily: "Helvetica-Bold", color: "#111827" },
    signDesig: { fontSize: 9, color: "#9CA3AF", marginTop: 2 },
    borderBottom: { position: "absolute", bottom: 0, left: 0, right: 0, height: 6, background: T },
    footerGen: { position: "absolute", bottom: 30, left: 70, fontSize: 8, color: "#D1D5DB" },
  });

  const reasonText = form.reason === "custom" ? form.customReason : REASONS[form.reason] || "";
  const gratitude = form.gratitudeNote || "I am grateful for the opportunities for professional and personal development provided during my tenure. I have enjoyed working with the team and value the experience gained here.";

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>RESIGNATION</Text>
          <Text style={styles.subtitle}>Formal Notification Letter</Text>
        </View>
        <Text style={styles.dateLine}>{"Dated: " + form.letterDate}</Text>
        <View style={styles.toBox}>
          <Text style={styles.toName}>{form.managerName || "Manager Name"}</Text>
          <Text style={styles.toSub}>{form.managerDesignation || "Designation"}{form.companyName ? ", " + form.companyName : ""}</Text>
        </View>
        <Text style={styles.body}>Dear {form.managerName ? form.managerName.split(" ")[0] : "Sir/Madam"},</Text>
        <Text style={styles.body}>
          I am writing to formally notify you of my resignation from the position of <Text style={styles.highlight}>{form.designation || "[Designation]"}</Text> 
          {form.department ? " in the " + form.department + " department" : ""}
          {form.companyName ? " at " + form.companyName : ""}
          {". My last working day will be "}
          <Text style={styles.highlight}>{form.lastWorkingDate || "[Last Working Date]"}</Text>, 
          serving a notice period of {form.noticePeriod || "30"} days.
        </Text>
        {reasonText !== "" && <Text style={styles.body}>{reasonText}</Text>}
        <Text style={styles.body}>{gratitude}</Text>
        <Text style={styles.body}>I will ensure a smooth transition and will complete all pending tasks before my last working day. Please let me know how I can assist during this transition period. Thank you for your support and guidance.</Text>
        <Text style={styles.body}>Yours sincerely,</Text>
        <View style={{ marginTop: 30 }}>
          {form.signature && <Image src={form.signature} style={styles.signImg} />}
          <View style={styles.signLine}>
            <Text style={styles.signName}>{form.employeeName || "Employee Name"}</Text>
            <Text style={styles.signDesig}>{form.designation || ""}</Text>
          </View>
        </View>
        <Text style={styles.footerGen}>Generated by DocMinty.com</Text>
        <View style={styles.borderBottom} />
      </Page>
    </Document>
  );
}
