"use client";
import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";

const REASONS = {
  personal: "I have decided to pursue a new opportunity that aligns more closely with my personal and professional goals.",
  relocation: "Due to relocation constraints, I am unable to continue in my current position.",
  health: "Due to personal health reasons, I am unable to continue in my current role.",
  higher: "I have been offered an opportunity to pursue higher education, which requires my full commitment.",
};

export default function ResignationMinimalTemplate({ form }) {
  const T = form.templateColor || "#111827";
  
  const styles = StyleSheet.create({
    page: { fontFamily: "Helvetica", fontSize: 10, color: "#374151", padding: "40 50" },
    header: { borderBottomWidth: 1.5, borderBottomColor: T, paddingBottom: 10, marginBottom: 24, flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" },
    title: { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#111827", textTransform: "uppercase", letterSpacing: 1 },
    date: { fontSize: 9, color: "#9CA3AF" },
    meta: { marginBottom: 24 },
    label: { fontSize: 7, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 2 },
    value: { fontSize: 10, fontFamily: "Helvetica-Bold", color: "#111827" },
    bodyText: { fontSize: 10, color: "#374151", lineHeight: 1.7, marginBottom: 12 },
    lastDay: { color: T, fontFamily: "Helvetica-Bold" },
    signRow: { marginTop: 40, flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" },
    signImg: { height: 35, marginBottom: 5, objectFit: "contain" },
    signLine: { borderTopWidth: 1, borderTopColor: "#111827", paddingTop: 5, width: 140 },
    signName: { fontSize: 10, fontFamily: "Helvetica-Bold", color: "#111827" },
    signGen: { fontSize: 7, color: "#D1D5DB", position: "absolute", bottom: 20, left: 50 },
  });

  const reasonText = form.reason === "custom" ? form.customReason : REASONS[form.reason] || "";
  const gratitude = form.gratitudeNote || "I am grateful for the opportunities for professional and personal development provided during my tenure. I have enjoyed working with the team and value the experience gained here.";

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Resignation Letter</Text>
          <Text style={styles.date}>{form.letterDate}</Text>
        </View>
        <View style={styles.meta}>
          <Text style={styles.label}>To</Text>
          <Text style={styles.value}>{form.managerName || "Manager Name"}</Text>
          <Text style={{ fontSize: 9, color: "#6B7280", marginTop: 1 }}>{form.managerDesignation || "Designation"}{form.companyName ? ", " + form.companyName : ""}</Text>
        </View>
        <Text style={styles.bodyText}>Dear {form.managerName ? form.managerName.split(" ")[0] : "Sir/Madam"},</Text>
        <Text style={styles.bodyText}>
          I am writing to formally resign from my position as <Text style={{ fontFamily: "Helvetica-Bold" }}>{form.designation || "[Designation]"}</Text> 
          {form.department ? " in the " + form.department + " department" : ""}. 
          My last working day will be <Text style={styles.lastDay}>{form.lastWorkingDate || "[Last Working Date]"}</Text>, 
          serving my notice period of {form.noticePeriod || "30"} days.
        </Text>
        {reasonText !== "" && <Text style={styles.bodyText}>{reasonText}</Text>}
        <Text style={styles.bodyText}>{gratitude}</Text>
        <Text style={styles.bodyText}>I will ensured all pending tasks are completed and a smooth handover is facilitated.</Text>
        <View style={styles.signRow}>
          <View>
            <Text style={styles.label}>Sincerely,</Text>
            {form.signature && <Image src={form.signature} style={styles.signImg} />}
            <View style={styles.signLine}>
              <Text style={styles.signName}>{form.employeeName || "Employee Name"}</Text>
            </View>
          </View>
        </View>
        <Text style={styles.signGen}>Generated by DocMinty.com</Text>
      </Page>
    </Document>
  );
}
